import { Script } from "scripting"
import { runEhAction, type EhAction } from "./ehAction"
import { GALLERY_CATEGORIES, QUICK_FILTERS, type GalleryCategoryKey, type QuickFilterKey } from "./tourist"

export type EhAssistantToolParams={action?:string;query?:string;category?:string;language?:string;galleryRef?:string;favoritesCategory?:number;limit?:number}
const categories=new Set(GALLERY_CATEGORIES.map(item=>item.key)),languages=new Set(QUICK_FILTERS.map(item=>item.key))
export function assistantToolAction(params:EhAssistantToolParams):EhAction|{error:string}{const action=String(params?.action||"").trim();if(action==="account.status")return{type:"account.status"};if(action==="search"){const query=String(params.query||"").trim(),category=params.category==null?undefined:String(params.category),language=params.language==null?undefined:String(params.language);if(!query)return{error:"搜索词不能为空。"};if(category&&!categories.has(category as any))return{error:"搜索分类无效。"};if(language&&!languages.has(language as any))return{error:"语言筛选无效。"};return{type:"search",query,category:category as GalleryCategoryKey|undefined,language:language as QuickFilterKey|undefined}}if(action==="gallery.detail"){const galleryRef=String(params.galleryRef||"").trim();return galleryRef?{type:"gallery.detail",galleryRef}:{error:"请先搜索并提供 galleryRef。"}}if(action==="favorites.list")return{type:"favorites.list",category:params.favoritesCategory,query:String(params.query||"").trim()};if(action==="history.list")return{type:"history.list",limit:params.limit};return{error:"不支持的 action。"}}
export function assistantToolPrivacySafe(value:unknown){const text=JSON.stringify(value);return !/https?:|\/g\/|"gid"|"token"|ipb_|igneous|apiuid|apikey|\/private\/|\/var\//i.test(text)}
export async function executeEhAssistantTool(params:EhAssistantToolParams):Promise<AssistantToolResponseResult>{const action=assistantToolAction(params);const result="error" in action?{ok:false,code:"INVALID_ACTION",stage:"validate",message:action.error}:await runEhAction(action);if(!assistantToolPrivacySafe(result))return{success:false,output:{userParts:[{type:"text",text:"工具结果被隐私边界拒绝。"}],assistantParts:[{type:"text",text:JSON.stringify({ok:false,code:"PRIVACY_REJECTED"})}]}};const text=JSON.stringify(result);return{success:Boolean(result.ok),output:{userParts:[{type:"text",text:result.ok?"E-Hentai 浏览器操作完成。":String((result as any).message||"操作未完成。")}],assistantParts:[{type:"text",text}]}}}
if(Script.env==="assistant_tool"){
 AssistantTool.registerApprovalRequest<EhAssistantToolParams>(async params=>({title:"E-Hentai 浏览器",message:`Assistant 请求执行只读操作：${String(params.action||"未知") }。将使用当前本机 E/Ex 会话，但不会返回 Cookie、画廊 URL、gid 或 token。`,primaryButtonLabel:"允许",secondaryButtonLabel:"取消"}))
 AssistantTool.registerExecuteToolWithApproval<EhAssistantToolParams>(async(params,{primaryConfirmed})=>primaryConfirmed?executeEhAssistantTool(params):{success:false,output:{userParts:[{type:"text",text:"操作已取消。"}],assistantParts:[{type:"text",text:JSON.stringify({ok:false,code:"CANCELLED"})}]}})
}
