const E_BASE="https://e-hentai.org/",EX_BASE="https://exhentai.org/",LOGIN_URL="https://e-hentai.org/bounce_login.php?b=d&bt=1-1",COOKIE_KEY="ehentai.account.cookies.v1",SITE_KEY="ehentai.account.site.v1",IMPORT_DIRECTORY="ehentai-cookie-import",IMPORT_FILE="cookies.json"
export const SAFARI_LOGIN_URL=LOGIN_URL
const AUTH_COOKIE_NAMES=new Set(["ipb_member_id","ipb_pass_hash","ipb_session_id","igneous"])
const fileManager:any=(globalThis as any).FileManager
export type GallerySite="e"|"ex"
export type StoredCookie={name:string;value:string;domain:string;path:string;isSecure?:boolean;isHTTPOnly?:boolean;isSessionOnly?:boolean;expiresDate?:string|null}
export type AccountStatus={loggedIn:boolean;memberIdPresent:boolean;passHashPresent:boolean;igneousPresent:boolean;site:GallerySite;eHentaiReachable:boolean|null;exAvailable:boolean|null}
export type AccountCredentialDependencies={fileManager:any;keychain:any;now:()=>number}
function keychain():any{const api=(globalThis as any).Keychain;if(!api)throw new Error("当前 Scripting 运行时未提供 Keychain API。");return api}
function dependencies():AccountCredentialDependencies{return{fileManager,keychain:keychain(),now:()=>Date.now()}}
function normalizeDomain(value:string){return String(value||"").trim().toLowerCase().replace(/^\./,"")}
function isEhDomain(domain:string){const value=normalizeDomain(domain);return value==="e-hentai.org"||value.endsWith(".e-hentai.org")||value==="exhentai.org"||value.endsWith(".exhentai.org")}
function normalizeExpiry(raw:any):string|null{const value=raw?.expiresDate??raw?.expirationDate??raw?.expires??null;if(value==null||value==="")return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString()}
export function sanitizeCookies(cookies:any[]):StoredCookie[]{const map=new Map<string,StoredCookie>();for(const raw of cookies||[]){const name=String(raw?.name||"").trim(),value=String(raw?.value||""),domain=String(raw?.domain||"").trim();if(!name||!value||!domain||!isEhDomain(domain))continue;const item={name,value,domain,path:String(raw?.path||"/"),isSecure:Boolean(raw?.isSecure??raw?.secure),isHTTPOnly:Boolean(raw?.isHTTPOnly??raw?.httpOnly),isSessionOnly:Boolean(raw?.isSessionOnly??raw?.session),expiresDate:normalizeExpiry(raw)};map.set(`${normalizeDomain(domain)}|${item.path}|${name}`,item)}return[...map.values()]}
function current(cookie:StoredCookie,now=Date.now()){return!cookie.expiresDate||!Number.isFinite(Date.parse(cookie.expiresDate))||Date.parse(cookie.expiresDate)>now}
function hasAuth(cookies:StoredCookie[]){const names=new Set(cookies.filter(cookie=>current(cookie)).map(cookie=>cookie.name));return names.has("ipb_member_id")&&names.has("ipb_pass_hash")}
export function loadCookies(api=keychain()):StoredCookie[]{try{const parsed=JSON.parse(String(api.get(COOKIE_KEY)||"[]"));return Array.isArray(parsed)?sanitizeCookies(parsed):[]}catch{return[]}}
function saveCookies(cookies:StoredCookie[],api=keychain()){const safe=sanitizeCookies(cookies);if(!hasAuth(safe))throw new Error("登录数据缺少 ipb_member_id 或 ipb_pass_hash。");if(!api.set(COOKIE_KEY,JSON.stringify(safe),{accessibility:"first_unlock_this_device",synchronizable:false}))throw new Error("登录 Cookie 写入 Keychain 失败。")}
let generation=0
export function getAccountSessionGeneration(){return generation}
function invalidate(){generation+=1;try{(globalThis as any).__ehentaiInvalidateGalleryCaches?.()}catch{}}
export function getActiveSite(api=keychain()):GallerySite{try{return api.get(SITE_KEY)==="ex"?"ex":"e"}catch{return"e"}}
export function setActiveSite(site:GallerySite,api=keychain()){if(!api.set(SITE_KEY,site,{accessibility:"first_unlock_this_device",synchronizable:false}))throw new Error("站点设置写入 Keychain 失败。");invalidate()}
export function getBaseUrl(site=getActiveSite()){return site==="ex"?EX_BASE:E_BASE}
export function getAccountStatus(api=keychain()):AccountStatus{const names=new Set(loadCookies(api).filter(cookie=>current(cookie)).map(cookie=>cookie.name));return{loggedIn:names.has("ipb_member_id")&&names.has("ipb_pass_hash"),memberIdPresent:names.has("ipb_member_id"),passHashPresent:names.has("ipb_pass_hash"),igneousPresent:names.has("igneous"),site:getActiveSite(api),eHentaiReachable:null,exAvailable:null}}
function domainMatches(host:string,domain:string){const normalized=normalizeDomain(domain),value=String(host||"").toLowerCase();return value===normalized||value.endsWith(`.${normalized}`)}
export function getCookieHeader(url:string){let target:URL;try{target=new URL(url)}catch{return""}const pairs=new Map<string,string>();for(const cookie of loadCookies()){if(!current(cookie)||!domainMatches(target.hostname,cookie.domain)||!(target.pathname||"/").startsWith(cookie.path||"/"))continue;pairs.set(cookie.name,cookie.value)}if(target.hostname==="e-hentai.org"&&!pairs.has("nw"))pairs.set("nw","1");return[...pairs.entries()].map(([name,value])=>`${name}=${value}`).join("; ")}
async function validateSite(site:GallerySite){const url=site==="ex"?EX_BASE:`${E_BASE}home.php`,cookie=getCookieHeader(url);if(!cookie)return false;try{const response=await fetch(url,{headers:{Cookie:cookie},timeout:20});const finalUrl=String(response.url||url);if(!response.ok||/forums\.e-hentai\.org\/index\.php\?act=Login|act=Login/i.test(finalUrl))return false;const text=await response.text();return site!=="ex"||!/sadpanda|kokomade/i.test(text)}catch{return false}}
export async function refreshAccountStatus():Promise<AccountStatus>{const base=getAccountStatus();if(!base.loggedIn)return base;return{...base,eHentaiReachable:await validateSite("e"),exAvailable:await validateSite("ex")}}
function parseCookieText(value:string){const text=String(value||"").trim();if(!text)throw new Error("Cookie 内容为空。");try{const parsed=JSON.parse(text);if(Array.isArray(parsed))return sanitizeCookies(parsed)}catch{}return sanitizeCookies(text.split(/;\s*/).map(part=>{const i=part.indexOf("=");return i>0?{name:part.slice(0,i).trim(),value:part.slice(i+1),domain:"e-hentai.org",path:"/",secure:true}:null}).filter(Boolean))}
export function importCookiesFromText(value:string){const cookies=parseCookieText(value);saveCookies(cookies);setActiveSite("e");return getAccountStatus()}
export function browserCookiePaths(manager=fileManager){const roots=[manager?.safariBrowserDirectory,manager?.appGroupDocumentsDirectory,manager?.documentsDirectory,manager?.safariBrowserStorageDirectory].map(value=>String(value||"").trim()).filter(Boolean);return[...new Set(roots)].map(root=>`${root}/${IMPORT_DIRECTORY}/${IMPORT_FILE}`)}
export async function importBrowserCookieDraft(manager=fileManager){for(const path of browserCookiePaths(manager)){try{if(!await manager.exists(path))continue;const payload=JSON.parse(String(await manager.readAsString(path)||"{}"));const cookies=sanitizeCookies(payload?.cookies||[]);if(hasAuth(cookies))return JSON.stringify(cookies)}catch{}}throw new Error("未找到有效浏览器 Cookie。请先在 Safari 登录后点击“🍪 已登录 · 获取 Cookie”。")}
export async function saveAndValidateCookieDraft(draft:string,api=keychain()){const cookies=parseCookieText(draft);saveCookies(cookies,api);if(!hasAuth(loadCookies(api)))throw new Error("Keychain 写入后校验失败。");setActiveSite("e",api);return refreshAccountStatus()}
export async function openSafariLogin(){const opened=await Safari.openURL(SAFARI_LOGIN_URL);if(!opened)throw new Error("无法打开系统浏览器。请手动用 Safari 打开 E-Hentai 登录页。")}
export async function signOut(input=dependencies()){const failed:string[]=[];for(const key of[COOKIE_KEY,SITE_KEY])try{if(input.keychain.remove(key)===false)failed.push(key)}catch{failed.push(key)}if(failed.length)throw new Error("退出登录时部分 Keychain 凭据未能清理，请重试。");invalidate()}
