const E_BASE="https://e-hentai.org/",EX_BASE="https://exhentai.org/",LOGIN_URL="https://e-hentai.org/bounce_login.php?b=d&bt=1-1",EX_SYNC_URL="https://exhentai.org/",COOKIE_KEY="ehentai.account.cookies.v1",SITE_KEY="ehentai.account.site.v1",SESSION_KEY="ehentai.account.session-generation.v1",IMPORT_FILE="ehviewer_cookie.txt",IMPORT_GM_KEY="ehviewer_cookie",LEGACY_IMPORT_DIRECTORY="ehentai-cookie-import",LEGACY_IMPORT_FILE="cookies.json"
export const SAFARI_LOGIN_URL=LOGIN_URL
const fileManager:any=(globalThis as any).FileManager
export type GallerySite="e"|"ex"
export type StoredCookie={name:string;value:string;domain:string;path:string;hostOnly?:boolean;isSecure?:boolean;isHTTPOnly?:boolean;isSessionOnly?:boolean;expiresDate?:string|null}
export type CookieAuthPresence={memberIdPresent:boolean;passHashPresent:boolean;igneousPresent:boolean;igneousStructurallyValid:boolean}
export type AccountStatus={loggedIn:boolean;memberIdPresent:boolean;passHashPresent:boolean;igneousPresent:boolean;site:GallerySite;eHentaiReachable:boolean|null;exAvailable:boolean|null}
export type AccountCredentialDependencies={fileManager:any;keychain:any;now:()=>number}
function keychain():any{const api=(globalThis as any).Keychain;if(!api)throw new Error("当前 Scripting 运行时未提供 Keychain API。");return api}
function dependencies():AccountCredentialDependencies{return{fileManager,keychain:keychain(),now:()=>Date.now()}}
function normalizeDomain(value:string){return String(value||"").trim().toLowerCase().replace(/^\./,"")}
function isEhDomain(domain:string){const value=normalizeDomain(domain);return value==="e-hentai.org"||value.endsWith(".e-hentai.org")||value==="exhentai.org"||value.endsWith(".exhentai.org")}
function normalizeExpiry(raw:any):string|null|undefined{const value=raw?.expiresDate??raw?.expirationDate??raw?.expires??null;if(value==null||value==="")return null;const numeric=typeof value==="number"?value:(/^\d+(?:\.\d+)?$/.test(String(value).trim())?Number(value):NaN),date=Number.isFinite(numeric)?new Date(numeric<1e12?numeric*1000:numeric):new Date(value);return Number.isNaN(date.getTime())?undefined:date.toISOString()}
export function sanitizeCookies(cookies:any[]):StoredCookie[]{const map=new Map<string,StoredCookie>();for(const raw of cookies||[]){const name=String(raw?.name||"").trim(),value=String(raw?.value||""),domain=String(raw?.domain||"").trim(),expiresDate=normalizeExpiry(raw);if(!name||!value||!domain||!isEhDomain(domain)||expiresDate===undefined)continue;const path=String(raw?.path||"/").trim();if(!path.startsWith("/"))continue;const item={name,value,domain,path,hostOnly:Boolean(raw?.hostOnly),isSecure:Boolean(raw?.isSecure??raw?.secure),isHTTPOnly:Boolean(raw?.isHTTPOnly??raw?.httpOnly),isSessionOnly:Boolean(raw?.isSessionOnly??raw?.session),expiresDate};map.set(`${normalizeDomain(domain)}|${item.path}|${name}`,item)}return[...map.values()]}
export function mergeCookies(existing:StoredCookie[],incoming:StoredCookie[]){const map=new Map<string,StoredCookie>();for(const cookie of[...sanitizeCookies(existing),...sanitizeCookies(incoming)])map.set(`${normalizeDomain(cookie.domain)}|${cookie.path}|${cookie.name}`,cookie);return[...map.values()]}
function current(cookie:StoredCookie,now=Date.now()){return!cookie.expiresDate||Date.parse(cookie.expiresDate)>now}
function domainMatches(host:string,cookie:StoredCookie){const normalized=normalizeDomain(cookie.domain),value=String(host||"").toLowerCase();return cookie.hostOnly?value===normalized:value===normalized||value.endsWith(`.${normalized}`)}
function pathMatches(requestPath:string,cookiePath:string){const request=requestPath||"/",path=cookiePath||"/";return request===path||(request.startsWith(path)&&(path.endsWith("/")||request.charAt(path.length)==="/"))}
function selectedCookiesFor(cookies:StoredCookie[],url:string,now=Date.now()){let target:URL;try{target=new URL(url)}catch{return new Map<string,StoredCookie>()}const selected=new Map<string,{cookie:StoredCookie;score:number}>();for(const cookie of cookies){if(!current(cookie,now)||!domainMatches(target.hostname,cookie)||!pathMatches(target.pathname,cookie.path))continue;const score=(normalizeDomain(cookie.domain)===target.hostname?10000:0)+(cookie.hostOnly?5000:0)+cookie.path.length;const existing=selected.get(cookie.name);if(!existing||score>existing.score)selected.set(cookie.name,{cookie,score})}return new Map([...selected].map(([name,value])=>[name,value.cookie]))}
export function isStructurallyValidIgneous(value:unknown){const text=String(value??"").trim();return Boolean(text)&&!/^(?:mystery|null|undefined|none|false|0)$/i.test(text)}
export function cookieAuthPresence(cookies:StoredCookie[],url:string,now=Date.now()):CookieAuthPresence{const selected=selectedCookiesFor(cookies,url,now),igneous=selected.get("igneous")?.value||"";return{memberIdPresent:selected.has("ipb_member_id"),passHashPresent:selected.has("ipb_pass_hash"),igneousPresent:Boolean(igneous),igneousStructurallyValid:isStructurallyValidIgneous(igneous)}}
export function cookieHeaderFor(cookies:StoredCookie[],url:string,now=Date.now()){let target:URL;try{target=new URL(url)}catch{return""}const selected=selectedCookiesFor(cookies,url,now);if(target.hostname==="e-hentai.org"&&!selected.has("nw"))selected.set("nw",{name:"nw",value:"1",domain:"e-hentai.org",path:"/"});return[...selected.values()].map(cookie=>`${cookie.name}=${cookie.value}`).join("; ")}
export function authenticatedHeadersFor(cookies:StoredCookie[],url:string){const cookie=cookieHeaderFor(cookies,url);return cookie?{Cookie:cookie}:{} as Record<string,string>}
function hasAuthForUrl(cookies:StoredCookie[],url=E_BASE+"home.php",now=Date.now()){const auth=cookieAuthPresence(cookies,url,now);return auth.memberIdPresent&&auth.passHashPresent}
export function loadCookies(api=keychain()):StoredCookie[]{try{const parsed=JSON.parse(String(api.get(COOKIE_KEY)||"[]"));return Array.isArray(parsed)?sanitizeCookies(parsed):[]}catch{return[]}}
function saveCookies(cookies:StoredCookie[],api=keychain()){const safe=sanitizeCookies(cookies);if(!hasAuthForUrl(safe))throw new Error("登录数据缺少可用于 E-Hentai 的 ipb_member_id 或 ipb_pass_hash。");if(!api.set(COOKIE_KEY,JSON.stringify(safe),{accessibility:"first_unlock_this_device",synchronizable:false}))throw new Error("登录 Cookie 写入 Keychain 失败。");return safe}
let memoryGeneration=0
export function getAccountSessionGeneration(api=keychain()){try{return Math.max(memoryGeneration,Number(api.get(SESSION_KEY)||0)||0)}catch{return memoryGeneration}}
function invalidate(api=keychain()){memoryGeneration=Math.max(memoryGeneration+1,getAccountSessionGeneration(api)+1);try{api.set(SESSION_KEY,String(memoryGeneration),{accessibility:"first_unlock_this_device",synchronizable:false})}catch{}try{(globalThis as any).__ehentaiInvalidateGalleryCaches?.()}catch{}}
export function getActiveSite(api=keychain()):GallerySite{try{return api.get(SITE_KEY)==="ex"?"ex":"e"}catch{return"e"}}
export function setActiveSite(site:GallerySite,api=keychain()){if(!api.set(SITE_KEY,site,{accessibility:"first_unlock_this_device",synchronizable:false}))throw new Error("站点设置写入 Keychain 失败。");invalidate(api);try{(globalThis as any).__ehAccountContextChanged?.(getAccountSessionGeneration(api))}catch{}}
export function getBaseUrl(site=getActiveSite()){return site==="ex"?EX_BASE:E_BASE}
export function routeUrlForSite(value:string,site=getActiveSite()){const url=new URL(value,getBaseUrl(site));if(url.hostname==="e-hentai.org"||url.hostname==="exhentai.org")url.hostname=new URL(getBaseUrl(site)).hostname;return url.toString()}
export function getAccountStatus(api=keychain()):AccountStatus{const cookies=loadCookies(api),e=cookieAuthPresence(cookies,E_BASE+"home.php"),ex=cookieAuthPresence(cookies,EX_BASE),site=getActiveSite(api);return{loggedIn:e.memberIdPresent&&e.passHashPresent,memberIdPresent:e.memberIdPresent,passHashPresent:e.passHashPresent,igneousPresent:ex.igneousStructurallyValid,site,eHentaiReachable:e.memberIdPresent&&e.passHashPresent,exAvailable:ex.memberIdPresent&&ex.passHashPresent&&ex.igneousStructurallyValid}}
export function getCookieHeader(url:string){return cookieHeaderFor(loadCookies(),url)}
export function productionRequestAuth(url:string,cookies=loadCookies()){return{headers:authenticatedHeadersFor(cookies,url),presence:cookieAuthPresence(cookies,url)}}
export async function validateSite(site:GallerySite,cookies=loadCookies()){const url=site==="ex"?EX_BASE:`${E_BASE}home.php`,context=productionRequestAuth(url,cookies);if(!context.presence.memberIdPresent||!context.presence.passHashPresent)return false;if(site==="ex"&&!context.presence.igneousStructurallyValid)return false;try{const response=await fetch(url,{headers:context.headers,signal:AbortSignal.timeout(20_000)});const finalUrl=String(response.url||url);if(!response.ok||/forums\.e-hentai\.org\/index\.php\?act=Login|act=Login/i.test(finalUrl))return false;const text=await response.text();return site!=="ex"||!/sadpanda|kokomade/i.test(text)}catch{return false}}
export async function refreshAccountStatus():Promise<AccountStatus>{const base=getAccountStatus();if(!base.loggedIn)return base;return{...base,eHentaiReachable:await validateSite("e"),exAvailable:await validateSite("ex")}}
export function parseCookieText(value:string){const text=String(value||"").trim();if(!text)throw new Error("Cookie 内容为空。");try{const parsed=JSON.parse(text);if(Array.isArray(parsed)){const safe=sanitizeCookies(parsed);if(safe.length)return safe}}catch{}const pairs=text.split(/;\s*/).map(part=>{const i=part.indexOf("=");return i>0?{name:part.slice(0,i).trim(),value:part.slice(i+1)}:null}).filter(Boolean) as Array<{name:string;value:string}>;return sanitizeCookies(pairs.map(item=>({...item,domain:"e-hentai.org",path:"/",secure:true})))}
function validCookieText(value:string){try{return hasAuthForUrl(parseCookieText(value))}catch{return false}}
function cookieRoots(manager=fileManager){const values=[manager?.documentsDirectory,manager?.appGroupDocumentsDirectory,manager?.iCloudDocumentsDirectory,manager?.safariBrowserDirectory].map(value=>String(value||"").trim()).filter(Boolean);return[...new Set(values)]}
export function browserCookiePaths(manager=fileManager){return cookieRoots(manager).map(root=>`${root}/${IMPORT_FILE}`)}
function legacyBrowserCookiePaths(manager=fileManager){const roots=[manager?.safariBrowserDirectory,manager?.appGroupDocumentsDirectory,manager?.documentsDirectory,manager?.safariBrowserStorageDirectory].map(value=>String(value||"").trim()).filter(Boolean);return[...new Set(roots)].map(root=>`${root}/${LEGACY_IMPORT_DIRECTORY}/${LEGACY_IMPORT_FILE}`)}
async function readGmCookieDraft(manager=fileManager){const root=String(manager?.safariBrowserStorageDirectory||"").trim().replace(/\/$/,"");if(!root)return"";let entries:any[]=[];try{entries=await manager.readDirectory(root)}catch{return""}for(const entry of entries){const candidate=String(entry?.path||entry?.url||entry?.filename||entry?.name||entry||"").trim(),path=candidate.startsWith("/")?candidate:`${root}/${candidate.replace(/^\.\//,"")}`;if(!path.endsWith(".json"))continue;try{const parsed=JSON.parse(String(await manager.readAsString(path)||"{}")),value=String(parsed?.[IMPORT_GM_KEY]??parsed?.values?.[IMPORT_GM_KEY]??"");if(validCookieText(value))return value.trim()}catch{}}return""}
export async function importBrowserCookieDraft(manager=fileManager){for(const path of browserCookiePaths(manager))try{if(await manager.exists(path)){const value=String(await manager.readAsString(path)||"").trim();if(validCookieText(value))return value}}catch{}for(const path of legacyBrowserCookiePaths(manager))try{if(!await manager.exists(path))continue;const payload=JSON.parse(String(await manager.readAsString(path)||"{}")),cookies=sanitizeCookies(payload?.cookies||[]);if(hasAuthForUrl(cookies))return JSON.stringify(cookies)}catch{}const gm=await readGmCookieDraft(manager);if(gm)return gm;throw new Error("未找到有效浏览器 Cookie。请先在 Safari 登录后点击 Cookie 助手，再返回导入。")}
async function clearBrowserCookieDrafts(manager=fileManager){for(const path of [...browserCookiePaths(manager),...legacyBrowserCookiePaths(manager)])try{if(await manager.exists(path))await manager.remove(path)}catch{}}
export async function saveAndValidateCookieDraft(draft:string,api=keychain()){const incoming=parseCookieText(draft),cookies=mergeCookies(loadCookies(api),incoming);if(!hasAuthForUrl(cookies))throw new Error("登录数据缺少可用于 E-Hentai 的认证 Cookie。");const eHentaiReachable=await validateSite("e",cookies);if(!eHentaiReachable)throw new Error("E-Hentai 登录验证失败，未覆盖当前本机登录。请回到 Safari 确认登录后重新获取 Cookie。");const exAvailable=await validateSite("ex",cookies);saveCookies(cookies,api);setActiveSite("e",api);return{...getAccountStatus(api),eHentaiReachable:true,exAvailable}}
export async function importAndValidateBrowserCookies(manager=fileManager,api=keychain()){const draft=await importBrowserCookieDraft(manager),status=await saveAndValidateCookieDraft(draft,api);await clearBrowserCookieDrafts(manager);return status}
export async function openSafariLogin(){const opened=await Safari.openURL(SAFARI_LOGIN_URL);if(!opened)throw new Error("无法打开系统浏览器。请手动用 Safari 打开 E-Hentai 登录页。")}
export async function openSafariExSync(){const opened=await Safari.openURL(EX_SYNC_URL);if(!opened)throw new Error("无法打开 ExHentai。请手动在 Safari 打开 exhentai.org。")}
export async function signOut(input=dependencies()){const failed:string[]=[];for(const key of[COOKIE_KEY,SITE_KEY])try{if(input.keychain.remove(key)===false)failed.push(key)}catch{failed.push(key)}if(failed.length)throw new Error("退出登录时部分 Keychain 凭据未能清理，请重试。");invalidate(input.keychain);try{(globalThis as any).__ehAccountContextChanged?.(getAccountSessionGeneration(input.keychain))}catch{}}
