import { GALLERY_CATEGORIES, QUICK_FILTERS, composeGallerySearchState, createGallerySearchTag, createHomeSearchState, normalizeAdvancedSearch, normalizeExcludedCategoryMask, type GalleryCategoryKey, type GallerySearchState, type GallerySearchTag, type QuickFilterKey } from "./tourist"
import { ensureTagTranslations, searchLocalTagSuggestions, translateTag } from "./tagTranslation"

export type AISearchIntent={plainText?:unknown;includeTags?:unknown;excludeTags?:unknown;category?:unknown;excludedCategories?:unknown;language?:unknown;minimumRating?:unknown;pageFrom?:unknown;pageTo?:unknown;searchTorrents?:unknown;showExpunged?:unknown}
export type AITagCandidate={concept:string;exclude:boolean;options:GallerySearchTag[]}
export type AINormalizedSearch={state:GallerySearchState;ambiguous:AITagCandidate[];unresolved:string[]}

export const AI_SEARCH_SCHEMA:JSONSchemaObject={type:"object",description:"E-Hentai search intent. Never output URLs or raw E-Hentai query syntax.",properties:{plainText:{type:"string",required:true,description:"Remaining title, artist, series, or uploader text. Empty when none."},includeTags:{type:"array",required:true,description:"Natural-language tag concepts to include. Preserve the user's Chinese phrases; do not invent canonical syntax.",items:{type:"string",description:"One tag concept."}},excludeTags:{type:"array",required:true,description:"Natural-language tag concepts to exclude. Do not put excluded gallery categories here.",items:{type:"string",description:"One excluded tag concept."}},category:{type:"string",required:true,description:"One included category key or empty: all,doujinshi,manga,artistcg,gamecg,western,non-h,imageset,cosplay,asianporn,misc."},excludedCategories:{type:"array",required:true,description:"Category keys explicitly excluded by the user.",items:{type:"string",description:"One category key."}},language:{type:"string",required:true,description:"Language key or empty: chinese,japanese,english,translated,speechless."},minimumRating:{type:"number",required:true,description:"Minimum rating 2,3,4,5; 0 if unspecified."},pageFrom:{type:"number",required:true,description:"Minimum page count; 0 if unspecified."},pageTo:{type:"number",required:true,description:"Maximum page count; 0 if unspecified."},searchTorrents:{type:"boolean",required:true,description:"Whether to require torrents."},showExpunged:{type:"boolean",required:true,description:"Whether to include expunged galleries."}}}

const categoryKeys=new Set<string>(GALLERY_CATEGORIES.map(item=>item.key)),quickKeys=new Set<string>(QUICK_FILTERS.map(item=>item.key))
function strings(value:unknown){return Array.isArray(value)?value.map(item=>String(item||"").trim()).filter(Boolean).slice(0,12):[]}
function positiveInt(value:unknown){const number=Number(value);return Number.isInteger(number)&&number>0?String(number).slice(0,8):""}
function rating(value:unknown):""|"2"|"3"|"4"|"5"{const text=String(Number(value)||"");return["2","3","4","5"].includes(text)?text as any:""}
function exactTerm(tag:GallerySearchTag,exclude=false){const prefix:Record<string,string>={artist:"a",cosplayer:"cos",character:"c",female:"f",group:"g",language:"l",male:"m",mixed:"x",other:"o",parody:"p",reclass:"r"};const p=prefix[tag.namespace],value=tag.tag.replace(/\\/g,"\\\\").replace(/"/g,'\\"');return p&&value?`${exclude?"-":""}${p}:"${value}$"`:""}
export function composeExcludedGalleryTags(plainText:string,tags:readonly GallerySearchTag[]){return[String(plainText||"").trim(),...tags.map(tag=>exactTerm(tag,true))].filter(Boolean).join(" ")}
function normalizedTag(value:{namespace:string;tag:string;translated?:string}){return createGallerySearchTag(value.namespace,value.tag,translateTag(value.namespace,value.tag)||value.translated||value.tag)}
export function resolveTagConcept(concept:string,exclude=false,search=searchLocalTagSuggestions):{resolved:GallerySearchTag[];ambiguous?:AITagCandidate;unresolved?:string}{const value=String(concept||"").trim();if(!value)return{resolved:[]};const suggestions=search(value,8).map(normalizedTag).filter(Boolean) as GallerySearchTag[];if(!suggestions.length)return{resolved:[],unresolved:value};const normalized=value.toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," "),exact=suggestions.filter(item=>item.display.toLowerCase()===normalized||`${item.namespace}:${item.tag}`===normalized||item.tag===normalized),candidates=exact.length?exact:suggestions;if(candidates.length===1)return{resolved:candidates};return{resolved:[],ambiguous:{concept:value,exclude,options:candidates.slice(0,6)}}}
export function createAISearchState(intent:AISearchIntent,choices:Record<string,GallerySearchTag[]>={},search=searchLocalTagSuggestions):AINormalizedSearch{if(!intent||typeof intent!=="object")throw new Error("AI 搜索结果结构无效，请重试。");const category=categoryKeys.has(String(intent.category))?String(intent.category) as GalleryCategoryKey:"all",language=quickKeys.has(String(intent.language))?String(intent.language) as QuickFilterKey:"none",base=createHomeSearchState("",category,language),included:GallerySearchTag[]=[],excluded:GallerySearchTag[]=[],ambiguous:AITagCandidate[]=[],unresolved:string[]=[];for(const [exclude,concepts] of [[false,strings(intent.includeTags)],[true,strings(intent.excludeTags)]] as const)for(const concept of concepts){const picked=choices[`${exclude?"-":"+"}${concept}`];if(picked?.length){(exclude?excluded:included).push(...picked);continue}const result=resolveTagConcept(concept,exclude,search);(exclude?excluded:included).push(...result.resolved);if(result.ambiguous)ambiguous.push(result.ambiguous);if(result.unresolved)unresolved.push(result.unresolved)}let mask=base.excludedCategoryMask;for(const key of strings(intent.excludedCategories))if(categoryKeys.has(key)&&key!=="all")mask|=GALLERY_CATEGORIES.find(item=>item.key===key)?.bit||0;mask=normalizeExcludedCategoryMask(mask);const minimumRating=rating(intent.minimumRating),pageFrom=positiveInt(intent.pageFrom),pageTo=positiveInt(intent.pageTo),searchTorrents=Boolean(intent.searchTorrents),showExpunged=Boolean(intent.showExpunged),advanced=normalizeAdvancedSearch({...base.advanced,enabled:Boolean(minimumRating||pageFrom||pageTo||searchTorrents||showExpunged),minimumRating,pageFrom,pageTo,searchTorrents,showExpunged});const keyword=composeExcludedGalleryTags(String(intent.plainText||"").trim(),excluded),state=composeGallerySearchState({...base,excludedCategoryMask:mask,advanced},keyword,included);return{state,ambiguous,unresolved}}
export async function requestAISearch(input:string):Promise<{intent:AISearchIntent;normalized:AINormalizedSearch}>{if(!Assistant.isAvailable)throw new Error("当前无法使用 Assistant，请先在 Scripting 的 Assistant 设置中配置可用模型。");await ensureTagTranslations();const intent=await Assistant.requestStructuredData<AISearchIntent>(`把以下自然语言转换为 E-Hentai 搜索意图：${String(input||"").trim()}。只表达用户明确要求；标签字段保留自然语言概念，不输出 URL、gid、token 或查询语法。`,AI_SEARCH_SCHEMA);return{intent,normalized:createAISearchState(intent)}}
export async function presentManagedAssistant(message="打开 E-Hentai 浏览器助手。你可以让我搜索画廊、查看云端收藏、最近历史，或检查一个搜索结果的安全元数据。"){if(!Assistant.isAvailable)throw new Error("当前无法使用 Assistant，请先在 Scripting 的 Assistant 设置中配置可用模型。");if(!Assistant.hasActiveConversation)await Assistant.startConversation({message,autoStart:false});await Assistant.present()}
export function safeGalleryAIMessage(detail:{title?:string;titleJpn?:string;category?:string;uploader?:string;rating?:number|null;pageCount?:number;tags?:Array<{namespace:string;names:string[]}>;comments?:string[]}){const payload={title:String(detail.title||"").slice(0,300),titleJpn:String(detail.titleJpn||"").slice(0,300),category:String(detail.category||"").slice(0,80),uploader:String(detail.uploader||"").slice(0,120),rating:detail.rating==null?null:Number(detail.rating),pageCount:Math.max(0,Number(detail.pageCount||0)),tags:(detail.tags||[]).slice(0,20).map(group=>({namespace:String(group.namespace||"").slice(0,40),names:(group.names||[]).slice(0,30).map(name=>String(name).slice(0,100))})),comments:(detail.comments||[]).slice(0,3).map(text=>String(text).replace(/https?:\/\/\S+/gi,"[链接已省略]").slice(0,500))};return`请基于以下安全画廊元数据帮助我理解、总结或寻找类似作品。不要索取或猜测任何私密定位信息或账号凭据。\n${JSON.stringify(payload)}`}
