import { GALLERY_CATEGORIES, QUICK_FILTERS, composeGallerySearchState, createGallerySearchTag, createHomeSearchState, normalizeAdvancedSearch, normalizeExcludedCategoryMask, type GalleryCategoryKey, type GallerySearchState, type GallerySearchTag, type QuickFilterKey } from "./tourist"
import { ensureTagTranslations, searchLocalTagSuggestions, translateTag } from "./tagTranslation"

export type AISearchIntent={plainText?:unknown;includeTags?:unknown;excludeTags?:unknown;category?:unknown;excludedCategories?:unknown;language?:unknown;minimumRating?:unknown;pageFrom?:unknown;pageTo?:unknown;searchTorrents?:unknown;showExpunged?:unknown}
export type AITagCandidate={concept:string;exclude:boolean;options:GallerySearchTag[]}
export type AINormalizedSearch={state:GallerySearchState;ambiguous:AITagCandidate[];unresolved:string[]}

export const AI_SEARCH_SCHEMA:JSONSchemaObject={type:"object",description:"E-Hentai search intent. Never output URLs or raw E-Hentai query syntax.",properties:{plainText:{type:"string",required:true,description:"Remaining title, artist, series, or uploader text. Empty when none."},includeTags:{type:"array",required:true,description:"Natural-language tag concepts to include. Preserve the user's Chinese phrases; do not invent canonical syntax.",items:{type:"string",description:"One tag concept."}},excludeTags:{type:"array",required:true,description:"Natural-language tag concepts to exclude. Do not put excluded gallery categories here.",items:{type:"string",description:"One excluded tag concept."}},category:{type:"string",required:true,description:"One included category key or empty: all,doujinshi,manga,artistcg,gamecg,western,non-h,imageset,cosplay,asianporn,misc."},excludedCategories:{type:"array",required:true,description:"Category keys explicitly excluded by the user.",items:{type:"string",description:"One category key."}},language:{type:"string",required:true,description:"Language key or empty: chinese,japanese,english,translated,speechless."},minimumRating:{type:"number",required:true,description:"Minimum rating 2,3,4,5; 0 if unspecified."},pageFrom:{type:"number",required:true,description:"Minimum page count; 0 if unspecified."},pageTo:{type:"number",required:true,description:"Maximum page count; 0 if unspecified."},searchTorrents:{type:"boolean",required:true,description:"Whether to require torrents."},showExpunged:{type:"boolean",required:true,description:"Whether to include expunged galleries."}}}

const categoryKeys=new Set<string>(GALLERY_CATEGORIES.map(item=>item.key)),quickKeys=new Set<string>(QUICK_FILTERS.map(item=>item.key))
function strings(value:unknown){return Array.isArray(value)?value.map(item=>String(item||"").trim()).filter(Boolean).slice(0,12):[]}
function positiveInt(value:unknown){const number=Number(value);return Number.isInteger(number)&&number>0?String(number).slice(0,8):""}
function rating(value:unknown):""|"2"|"3"|"4"|"5"{const text=String(Number(value)||"");return["2","3","4","5"].includes(text)?text as any:""}
function exactTerm(tag:GallerySearchTag,exclude=false){const prefix:Record<string,string>={artist:"a",cosplayer:"cos",character:"c",female:"f",group:"g",language:"l",male:"m",mixed:"x",other:"o",parody:"p",reclass:"r"};const p=prefix[tag.namespace],value=tag.tag.replace(/\\/g,"\\\\").replace(/"/g,'\\"');return p&&value?`${exclude?"-":""}${p}:"${value}$"`:""}
export function composeExcludedGalleryTags(plainText:string,tags:readonly GallerySearchTag[]){return[String(plainText||"").trim(),...tags.map(tag=>exactTerm(tag,true))].filter(Boolean).join(" ")}
function normalizedTag(value:{namespace:string;tag:string;translated?:string}){return createGallerySearchTag(value.namespace,value.tag,translateTag(value.namespace,value.tag)||value.translated||value.tag)}
export function resolveTagConcept(concept:string,exclude=false,search=searchLocalTagSuggestions):{resolved:GallerySearchTag[];ambiguous?:AITagCandidate;unresolved?:string}{const value=String(concept||"").trim();if(!value)return{resolved:[]};const suggestions=search(value,8).map(normalizedTag).filter(Boolean) as GallerySearchTag[];if(!suggestions.length)return{resolved:[],unresolved:value};const normalized=value.toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," "),exact=suggestions.filter(item=>item.display.toLowerCase()===normalized||`${item.namespace}:${item.tag}`===normalized||item.tag===normalized),candidates=exact.length?exact:suggestions;if(candidates.length===1)return{resolved:candidates};return{resolved:[],ambiguous:{concept:value,exclude,options:candidates.slice(0,6)}}}
export function createAISearchState(intent:AISearchIntent,choices:Record<string,GallerySearchTag[]>={},search=searchLocalTagSuggestions):AINormalizedSearch{if(!intent||typeof intent!=="object")throw new Error("AI 搜索结果结构无效，请重试。");const category=categoryKeys.has(String(intent.category))?String(intent.category) as GalleryCategoryKey:"all",language=quickKeys.has(String(intent.language))?String(intent.language) as QuickFilterKey:"none",base=createHomeSearchState("",category,language),included:GallerySearchTag[]=[],excluded:GallerySearchTag[]=[],ambiguous:AITagCandidate[]=[],unresolved:string[]=[];for(const [exclude,concepts] of [[false,strings(intent.includeTags)],[true,strings(intent.excludeTags)]] as const)for(const concept of concepts){const picked=choices[`${exclude?"-":"+"}${concept}`];if(picked?.length){(exclude?excluded:included).push(...picked);continue}const result=resolveTagConcept(concept,exclude,search);(exclude?excluded:included).push(...result.resolved);if(result.ambiguous)ambiguous.push(result.ambiguous);if(result.unresolved)unresolved.push(result.unresolved)}let mask=base.excludedCategoryMask;for(const key of strings(intent.excludedCategories))if(categoryKeys.has(key)&&key!=="all")mask|=GALLERY_CATEGORIES.find(item=>item.key===key)?.bit||0;mask=normalizeExcludedCategoryMask(mask);const minimumRating=rating(intent.minimumRating),pageFrom=positiveInt(intent.pageFrom),pageTo=positiveInt(intent.pageTo),searchTorrents=Boolean(intent.searchTorrents),showExpunged=Boolean(intent.showExpunged),advanced=normalizeAdvancedSearch({...base.advanced,enabled:Boolean(minimumRating||pageFrom||pageTo||searchTorrents||showExpunged),minimumRating,pageFrom,pageTo,searchTorrents,showExpunged});const keyword=composeExcludedGalleryTags(String(intent.plainText||"").trim(),excluded),state=composeGallerySearchState({...base,excludedCategoryMask:mask,advanced},keyword,included);return{state,ambiguous,unresolved}}
async function requestStreamingJson<T>(prompt:string):Promise<T>{const stream=await Assistant.requestStreaming({messages:{role:"user",content:prompt}});let text="";for await(const chunk of stream)if(chunk.type==="text")text+=chunk.content;const source=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");let value:unknown;try{value=JSON.parse(source)}catch{throw new Error("AI 返回的结构无效，请重试。")}if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("AI 返回的结构无效，请重试。");return value as T}
async function requestStructured<T>(prompt:string,schema:JSONSchemaObject):Promise<T>{try{return await Assistant.requestStructuredData<T>(prompt,schema)}catch(error){if(!/stream must be set to true/i.test(String((error as any)?.message||error)))throw error;return requestStreamingJson<T>(`${prompt}\n只输出符合该 JSON Schema 的对象，不要 Markdown：${JSON.stringify(schema)}`)}}
export async function requestAISearch(input:string):Promise<{intent:AISearchIntent;normalized:AINormalizedSearch}>{if(!Assistant.isAvailable)throw new Error("当前无法使用 Assistant，请先在 Scripting 的 Assistant 设置中配置可用模型。");await ensureTagTranslations();const prompt=`把以下自然语言转换为 E-Hentai 搜索意图：${String(input||"").trim()}。只表达用户明确要求；标签字段保留自然语言概念，不输出 URL、gid、token 或查询语法。`;const intent=await requestStructured<AISearchIntent>(prompt,AI_SEARCH_SCHEMA);return{intent,normalized:createAISearchState(intent)}}
const AI_RECOMMENDATION_PLAN_SCHEMA:JSONSchemaObject={type:"object",description:"One to three validated E-Hentai search intents for candidate discovery. Never output URLs or raw query syntax.",properties:{plans:{type:"array",required:true,description:"One to three alternative search intents, most specific first.",items:{type:"object",description:"One validated search intent.",properties:{plainText:{type:"string",required:true,description:"Safe plain text only."},includeTags:{type:"array",required:true,description:"Natural-language include tag concepts.",items:{type:"string",description:"One concept."}},excludeTags:{type:"array",required:true,description:"Natural-language exclude tag concepts.",items:{type:"string",description:"One concept."}},category:{type:"string",required:true,description:"Category key or empty."},excludedCategories:{type:"array",required:true,description:"Excluded category keys.",items:{type:"string",description:"One key."}},language:{type:"string",required:true,description:"Language key or empty."},minimumRating:{type:"number",required:true,description:"2,3,4,5 or 0."},pageFrom:{type:"number",required:true,description:"Minimum pages or 0."},pageTo:{type:"number",required:true,description:"Maximum pages or 0."},searchTorrents:{type:"boolean",required:true,description:"Require torrents."},showExpunged:{type:"boolean",required:true,description:"Include expunged."}}}}}}
export async function requestAIRecommendationPlans(input:string):Promise<AINormalizedSearch[]>{if(!Assistant.isAvailable)throw new Error("当前无法使用 Assistant，请先在 Scripting 的 Assistant 设置中配置可用模型。");await ensureTagTranslations();const prompt=`把用户偏好拆成最多 3 个用于发现真实候选的 E-Hentai 搜索意图。模糊概念可分别使用可验证标签概念、标题同义词、较宽泛相关词；不要直接推荐画廊。只表达用户明确要求；不输出 URL、gid、token 或查询语法。用户偏好：${String(input||"").trim()}`;const raw=await requestStructured<any>(prompt,AI_RECOMMENDATION_PLAN_SCHEMA),plans=Array.isArray(raw?.plans)?raw.plans.slice(0,3):[];if(!plans.length)throw new Error("AI 推荐计划结构无效，请重试。");return plans.map(intent=>createAISearchState(intent))}

export type SafeRecommendationCandidate={candidateId:string;title:string;titleJpn:string;category:string;uploader:string;pageCount:number;rating:number|null;ratingCount:number;tags:string[]}
export type RankedRecommendation={candidateId:string;reason:string}
const AI_RECOMMENDATION_RANK_SCHEMA:JSONSchemaObject={type:"object",description:"Rank only supplied candidate IDs. Never output URLs, gallery identifiers, query syntax or new candidates.",properties:{recommendations:{type:"array",required:true,description:"Three to five ranked supplied candidates.",items:{type:"object",description:"One candidate ranking.",properties:{candidateId:{type:"string",required:true,description:"An existing candidate ID only."},reason:{type:"string",required:true,description:"Short Chinese reason based only on supplied metadata."}}}}}}
function safeRecommendationText(value:unknown,limit:number){return String(value||"").replace(/https?:\/\/\S+/gi,"[链接已省略]").replace(/\b(?:gid|token|cookie|ipb_|apiuid|apikey)\b\s*[:=]?\s*\S*/gi,"[已省略]").replace(/\s+/g," ").trim().slice(0,limit)}
export function defaultRecommendationRanks(candidates:SafeRecommendationCandidate[]):RankedRecommendation[]{return candidates.slice(0,5).map(candidate=>({candidateId:candidate.candidateId,reason:safeRecommendationText(`匹配真实搜索条件 · ${candidate.pageCount||"未知"} 页`,120)}))}
export function validateRecommendationRanking(value:unknown,candidates:SafeRecommendationCandidate[]):RankedRecommendation[]{const allowed=new Set(candidates.map(candidate=>candidate.candidateId)),items=Array.isArray((value as any)?.recommendations)?(value as any).recommendations:[],out:RankedRecommendation[]=[],seen=new Set<string>();for(const item of items){const candidateId=String(item?.candidateId||"");if(!allowed.has(candidateId)||seen.has(candidateId))continue;const reason=safeRecommendationText(item?.reason,160);if(!reason)continue;seen.add(candidateId);out.push({candidateId,reason});if(out.length===5)break}return out}
export async function rankRecommendationCandidates(preference:string,candidates:SafeRecommendationCandidate[]):Promise<RankedRecommendation[]>{if(!Assistant.isAvailable)throw new Error("当前无法使用 Assistant，请先在 Scripting 的 Assistant 设置中配置可用模型。");const safeCandidates=candidates.slice(0,12).map(candidate=>({...candidate,title:safeRecommendationText(candidate.title,300),titleJpn:safeRecommendationText(candidate.titleJpn,300),category:safeRecommendationText(candidate.category,80),uploader:safeRecommendationText(candidate.uploader,120),tags:candidate.tags.slice(0,20).map(tag=>safeRecommendationText(tag,80))}));const prompt=`根据用户偏好和候选的安全元数据，返回 3 到 5 个最合适的候选排序。只能引用提供的 candidateId，不能创造候选；reason 用简短中文说明匹配点。不要输出 URL、查询语法、Cookie、gid 或 token。\n${JSON.stringify({preference:safeRecommendationText(preference,600),candidates:safeCandidates})}`;const ranked=validateRecommendationRanking(await requestStructured<unknown>(prompt,AI_RECOMMENDATION_RANK_SCHEMA),safeCandidates);return ranked.length?ranked:defaultRecommendationRanks(safeCandidates)}
export async function presentManagedAssistant(message="打开 E-Hentai 浏览器助手。你可以让我搜索画廊、查看云端收藏、最近历史，或检查一个搜索结果的安全元数据。"){if(!Assistant.isAvailable)throw new Error("当前无法使用 Assistant，请先在 Scripting 的 Assistant 设置中配置可用模型。");if(!Assistant.hasActiveConversation)await Assistant.startConversation({message,autoStart:false});await Assistant.present()}
export function safeGalleryAIMessage(detail:{title?:string;titleJpn?:string;category?:string;uploader?:string;rating?:number|null;pageCount?:number;tags?:Array<{namespace:string;names:string[]}>;comments?:string[]}){const payload={title:String(detail.title||"").slice(0,300),titleJpn:String(detail.titleJpn||"").slice(0,300),category:String(detail.category||"").slice(0,80),uploader:String(detail.uploader||"").slice(0,120),rating:detail.rating==null?null:Number(detail.rating),pageCount:Math.max(0,Number(detail.pageCount||0)),tags:(detail.tags||[]).slice(0,20).map(group=>({namespace:String(group.namespace||"").slice(0,40),names:(group.names||[]).slice(0,30).map(name=>String(name).slice(0,100))})),comments:(detail.comments||[]).slice(0,3).map(text=>String(text).replace(/https?:\/\/\S+/gi,"[链接已省略]").slice(0,500))};return`请基于以下安全画廊元数据帮助我理解、总结或寻找类似作品。不要索取或猜测任何私密定位信息或账号凭据。\n${JSON.stringify(payload)}`}
