import { Script } from "scripting"

const owner = "tudoutematou", repo = "scripting-ehentai", branch = "feat/0.8-ui-ux-consolidation"
const fileManager: any = (globalThis as any).FileManager
const root = (Script as any).directory as string
const join = (...parts: string[]) => parts.filter(Boolean).join("/")
async function put(path: string, message: string, content: string) { const remote = await GitHub.getContent({ owner, repo, path, ref: branch }) as { sha: string }; return GitHub.putContent({ owner, repo, path, message, content, sha: remote.sha, branch }) }
async function main() {
  const allowed = await GitHub.requestPermissions(["read_contents", "write_contents"])
  if (!allowed.includes("read_contents") || !allowed.includes("write_contents")) throw new Error("GitHub 读写权限未授予")
  const commits = await Promise.all(["GalleryFlow.tsx", "LibraryScene.tsx"].map(async file => put(`src/${file}`, "ui: unify gallery lists and filters", await fileManager.readAsString(join(root, file)))))
  const progress = `# DEV_PROGRESS — 0.8 UI/UX Consolidation\n\nStart base: accepted 0.7 head \`74660b5138458b09d89947254108bd8121b60701\`\nTask commit: \`a263d5bc5c19f50e505ec5b7f4bf58fc7a1e16ad\`\nBranch: \`feat/0.8-ui-ux-consolidation\`\n\n## Current phase\nPackages A–B complete.\n\n## Completed\n- **A / Navigation + Home**: user-intent Home hierarchy for search/browse, discovery, library, account/settings and external destinations.\n- **B / Gallery lists + Search**: shared \`GalleryRow\` is now reused for results, Home and Library gallery summaries; title/category/secondary metadata hierarchy is consistent. Filter category and language options are compact native sections without narrow-screen horizontal wrapping. Search pagination is visually secondary but explicit.\n- Reused existing native controls/components only; no dependency, search parameter, network/parser/store change.\n\n## Verification\n- \`src/runSelfTests.ts\`: passed (29 items).\n- \`src/runActionSmoke.ts\`: passed; typed \`galleryRef\` boundary and detail action remain intact.\n- DEV script \`E-Hentai 浏览器 DEV\` launch invoked; interactive Navigation session stayed active through the 45-second CLI window with no startup exception output.\n\n## Preserve\n- All accepted 0.7 feature families and safe storage/network/privacy behavior.\n- Stable local \`E-Hentai 浏览器\` remains untouched.\n- Runtime target is \`E-Hentai 浏览器 DEV\`.\n\n## Accepted PLATFORM_GAP — do not reopen in 0.8\n- Reverse image search upload path/multipart behavior unverified.\n- Rating submission authenticated API/form path unverified.\n- Comment post/edit action + CSRF/edit-ownership path unverified.\n\n## Work order\nA. App navigation + Home — completed\nB. Gallery lists + Search/Filter — completed\nC. Gallery Detail — next\nD. Library\nE. Downloads/offline\nF. Reader\nG. Account/Settings/maintenance\nH. UI copy/state/consistency sweep\n\n## Next step\nBegin Package C. Preserve existing favorite/download/bookmark behavior while separating identity, reading, ownership, relationships and resource actions into a clear Detail hierarchy.\n`
  const checkpoint = await put("DEV_PROGRESS.md", "chore: checkpoint package B", progress)
  console.log(JSON.stringify({ sourceCommits: commits.map(value => value.commit?.sha), checkpoint: checkpoint.commit?.sha }, null, 2))
}
main().catch(console.error).finally(() => Script.exit())
