import type { DetailExtractData, PreviewPageLink, GalleryTag } from "./extractors"

export type RatingCredentials = { gid: number; token: string; apiUid: number; apiKey: string }
export type RatingResult = { rating: number; ratingCount: number }
export type TorrentItem = { name: string; posted: string; downloadUrl: string }
export type GalleryComment = { id:number; author:string; posted:string; text:string; score:number; canEdit:boolean; canVoteUp:boolean; canVoteDown:boolean; voted:-1|0|1 }
export type CommentVoteResult = { id:number; score:number; voted:-1|0|1 }
export type ArchiveOption = { name:string; resolution:string; original:boolean }

function decodeHtml(value: string): string { const named: Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "}; return String(value||"").replace(/&#(\d+);/g,(_,c)=>String.fromCharCode(Number(c))).replace(/&#x([0-9a-f]+);/gi,(_,c)=>String.fromCharCode(parseInt(c,16))).replace(/&([a-z]+);/gi,(all,n)=>named[String(n).toLowerCase()]??all) }
function cleanText(value:string):string { return decodeHtml(String(value||"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<br\s*\/?>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim() }
function absoluteUrl(value:string,baseUrl:string):string { const decoded=decodeHtml(String(value||"").trim()); if(!decoded)return""; try{return new URL(decoded,baseUrl).toString()}catch{return decoded} }
function getAttribute(tag:string,name:string):string { const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"); const match=tag.match(new RegExp(`\\b${escaped}\\s*=\\s*(["'])(.*?)\\1`,"i")); return match?decodeHtml(match[2]):"" }
function escapeRegex(value:string):string{return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function findElementInnerById(html:string,id:string):string { const e=escapeRegex(id); const m=html.match(new RegExp(`<([a-z0-9]+)\\b[^>]*\\bid\\s*=\\s*(["'])${e}\\2[^>]*>([\\s\\S]*?)<\\/\\1>`,"i")); return m?m[3]:"" }
function findElementTextById(html:string,id:string):string{return cleanText(findElementInnerById(html,id))}
function findIdStart(html:string,id:string,fromIndex=0):number { const e=escapeRegex(id); const p=new RegExp(`<[a-z0-9]+\\b[^>]*\\bid\\s*=\\s*(["'])${e}\\1[^>]*>`,"i"); const m=p.exec(html.slice(fromIndex)); return m?fromIndex+(m.index||0):-1 }
function sliceSection(html:string,startId:string,endIds:string[]):string { const start=findIdStart(html,startId); if(start<0)return""; let end=html.length; for(const id of endIds){const c=findIdStart(html,id,start+1);if(c>=0&&c<end)end=c} return html.slice(start,end) }
function cssUrl(style:string,baseUrl:string):string { const m=String(style||"").match(/url\((['"]?)(.*?)\1\)/i); return m?absoluteUrl(m[2],baseUrl):"" }
function findClassText(html:string,className:string):string { const e=escapeRegex(className); const m=html.match(new RegExp(`<([a-z0-9]+)\\b[^>]*class\\s*=\\s*(["'])[^"']*\\b${e}\\b[^"']*\\2[^>]*>([\\s\\S]*?)<\\/\\1>`,"i")); return m?cleanText(m[3]):"" }
function parseMetadata(html:string):Record<string,string>{const block=sliceSection(html,"gdd",["gdr","gdf","gd4"]);const out:Record<string,string>={};for(const row of block.match(/<tr\b[^>]*>[\s\S]*?<\/tr>/gi)||[]){const cells=[...row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(m=>cleanText(m[1]));if(cells.length>=2){const k=cells[0].replace(/:$/,"").trim(),v=cells[1].trim();if(k&&v)out[k]=v}}return out}
function parseTags(html:string,baseUrl:string):Array<{namespace:string;tags:GalleryTag[]}>{const block=sliceSection(html,"taglist",["tagmenu_act","tagmenu_new","gwrd","gd5"]);const result:Array<{namespace:string;tags:GalleryTag[]}>=[];for(const row of block.match(/<tr\b[^>]*>[\s\S]*?<\/tr>/gi)||[]){const cells=[...row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)];if(cells.length<2)continue;const namespace=cleanText(cells[0][1]).replace(/:$/,"").trim();const tags=[...cells[1][1].matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map(m=>({name:cleanText(m[2]).split("|")[0].trim(),searchUrl:absoluteUrl(getAttribute(`<a ${m[1]}>`,"href"),baseUrl)})).filter(t=>t.name);if(namespace&&tags.length)result.push({namespace,tags})}return result}
function parsePreviewPages(html:string):number{let max=1;for(const m of html.matchAll(/<a\b[^>]*href\s*=\s*(["'])[^"']*[?&]p=(\d+)[^"']*\1[^>]*>([\s\S]*?)<\/a>/gi)){const text=Number(cleanText(m[3]));if(Number.isFinite(text)&&text>max)max=text;else max=Math.max(max,Number(m[2])+1)}return max}
function parsePreviewStyle(style:string,baseUrl:string){const text=decodeHtml(String(style||""));const w=text.match(/(?:^|;)\s*width\s*:\s*(\d+)px/i),h=text.match(/(?:^|;)\s*height\s*:\s*(\d+)px/i),p=text.match(/background-position\s*:\s*(-?\d+)(?:px)?\s+(-?\d+)(?:px)?/i)||text.match(/\)\s*(-?\d+)(?:px)?\s+(-?\d+)(?:px)?/i);return{thumb:cssUrl(text,baseUrl),thumbX:p?Math.abs(Number(p[1]||0)):0,thumbY:p?Math.abs(Number(p[2]||0)):0,thumbWidth:w?Number(w[1]):0,thumbHeight:h?Number(h[1]):0}}
function findPreviewSpriteStyle(html:string,anchorIndex:number,inner:string):string { const insideMatches=[...inner.matchAll(/<[^>]+\bstyle\s*=\s*(["'])([^"']*url\([^"']*)\1[^>]*>/gi)],inside=insideMatches.length?insideMatches[insideMatches.length-1][2]:"";if(inside)return inside;const before=html.slice(Math.max(0,anchorIndex-1200),anchorIndex),container=Math.max(before.search(/<[^>]+\bclass\s*=\s*(["'])[^"']*\b(?:gdtm|gdts|gdtl)\b[^"']*\1[^>]*>[\s\S]*$/i),before.lastIndexOf("</a>")),scope=before.slice(Math.max(0,container)),matches=[...scope.matchAll(/<[^>]+\bstyle\s*=\s*(["'])([^"']*url\([^"']*)\1[^>]*>/gi)];return matches.length?matches[matches.length-1][2]:"" }
export function parsePreviewPageHtml(html:string,baseUrl:string):PreviewPageLink[]{const links:PreviewPageLink[]=[];const seen=new Set<string>();const pattern=/<a\b[^>]*href\s*=\s*(["'])([^"']*\/s\/[^"']+)\1[^>]*>([\s\S]*?)<\/a>/gi;for(const m of html.matchAll(pattern)){const pageUrl=absoluteUrl(m[2],baseUrl);if(!pageUrl||seen.has(pageUrl))continue;const inner=m[3],title=inner.match(/\btitle\s*=\s*(["'])(.*?)\1/i),img=inner.match(/<img\b[^>]*>/i),alt=img?getAttribute(img[0],"alt"):"",idx=`${title?.[2]||""} ${alt}`.match(/(?:Page\s+)?([\d,]+)/i),spriteStyle=findPreviewSpriteStyle(html,m.index||0,inner),sprite=spriteStyle?parsePreviewStyle(spriteStyle,baseUrl):null;let thumb=sprite?.thumb||"",thumbX=sprite?.thumbX||0,thumbY=sprite?.thumbY||0,thumbWidth=sprite?.thumbWidth||0,thumbHeight=sprite?.thumbHeight||0;if(!thumb&&img)thumb=absoluteUrl(getAttribute(img[0],"data-src")||getAttribute(img[0],"src"),baseUrl);links.push({index:idx?Number(idx[1].replace(/,/g,"")):0,pageUrl,thumb,thumbX,thumbY,thumbWidth,thumbHeight});seen.add(pageUrl)}return links}
function parseCover(html:string,baseUrl:string):string{const block=sliceSection(html,"gd1",["gd2","gmid"]);const styled=block.match(/<[^>]+\bstyle\s*=\s*(["'])(.*?)\1[^>]*>/i);return styled?cssUrl(styled[2],baseUrl):""}
function parseCategory(html:string):string{const block=sliceSection(html,"gdc",["gdn","gdd"]);return findClassText(block,"cn")||findClassText(block,"cs")}
function detectPageError(text:string):string{if(/This gallery is unavailable/i.test(text))return"该画廊不可用。";if(/pining for the fjords/i.test(text))return"该画廊已被移除。";if(/And if you choose to ignore this warning/i.test(text))return"该画廊需要先在网页端确认警告。";return""}
function parseFavoriteInfo(html:string){const text=findElementTextById(html,"gdf");return{isFavorited:Boolean(text)&&!/add\s+to\s+favorites/i.test(text),favoriteName:/add\s+to\s+favorites/i.test(text)?"":text}}
function parseComments(html:string):GalleryComment[]{const out:GalleryComment[]=[];const blocks=[...html.matchAll(/<div\b[^>]*\bclass\s*=\s*(["'])[^"']*\bc3\b[^"']*\1[^>]*>([\s\S]*?)<\/div>([\s\S]*?)(?=<div\b[^>]*\bclass\s*=\s*(["'])[^"']*\bc3\b|$)/gi)];for(const block of blocks){const meta=cleanText(block[2]),tail=block[3],body=tail.match(/<div\b[^>]*\bclass\s*=\s*(["'])[^"']*\bc6\b[^"']*\1[^>]*>([\s\S]*?)<\/div>/i),text=cleanText(body?.[2]||"");if(!text)continue;const posted=(meta.match(/\d{4}[-/]\d{1,2}[-/]\d{1,2}[^\s]*/)?.[0]||meta.match(/\b\d+\s+(?:days?|hours?|minutes?)\s+ago\b/i)?.[0]||"").slice(0,120),author=meta.replace(posted,"").replace(/\b(?:posted|by)\b[:\s]*/ig,"").trim().slice(0,120),id=Number(tail.match(/(?:name|id)\s*=\s*(["'])c(\d+)\1/i)?.[2]||tail.match(/comment[_-]?id[^\d]*(\d+)/i)?.[1]||0),actions=cleanText(tail.match(/<div\b[^>]*\bclass\s*=\s*(["'])[^"']*\bc4\b[^"']*\1[^>]*>([\s\S]*?)<\/div>/i)?.[2]||""),score=Number(cleanText(tail.match(/<div\b[^>]*\bclass\s*=\s*(["'])[^"']*\bc5\b[^"']*\1[^>]*>([\s\S]*?)<\/div>/i)?.[2]||"0").match(/-?\d+/)?.[0]||0),voteText=cleanText(tail.match(/<div\b[^>]*\bclass\s*=\s*(["'])[^"']*\bc7\b[^"']*\1[^>]*>([\s\S]*?)<\/div>/i)?.[2]||"");out.push({id,author,posted,text:text.slice(0,1000),score,canEdit:/\bEdit\b/i.test(actions),canVoteUp:/Vote\+/i.test(actions),canVoteDown:/Vote-/i.test(actions),voted:/\+1|up/i.test(voteText)?1:/-1|down/i.test(voteText)?-1:0})}return out.slice(0,100)}
function findActionUrl(html:string,baseUrl:string,needle:string):string{for(const m of html.matchAll(/<a\b[^>]*>([\s\S]*?)<\/a>/gi)){const tag=m[0],label=cleanText(m[1]),title=`${getAttribute(tag,"title")} ${label} ${tag}`;if(!new RegExp(needle,"i").test(title))continue;const popup=getAttribute(tag,"onclick").match(/popUp\(\s*['"]([^'"]+)['"]/i)?.[1];const value=popup||getAttribute(tag,"href");if(value)return absoluteUrl(value,baseUrl)}return""}
function normalizeTorrentDownloadUrl(value:string):string { const marker=value.indexOf("?p="); return marker>=0?value.slice(0,marker):value }
export function parseTorrentListHtml(html:string,baseUrl:string):TorrentItem[]{const items:TorrentItem[]=[];const seen=new Set<string>();for(const form of String(html||"").match(/<form\b[^>]*>[\s\S]*?<\/form>/gi)||[]){const anchors=[...form.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map(match=>({href:absoluteUrl(getAttribute(`<a ${match[1]}>`,`href`),baseUrl),text:cleanText(match[2])}));const download=anchors.find(item=>item.href&&(/\bdownload\b/i.test(item.text)||/[?&]p=/.test(item.href)));if(!download)continue;const downloadUrl=normalizeTorrentDownloadUrl(download.href);if(!downloadUrl||seen.has(downloadUrl))continue;const text=cleanText(form);const posted=(text.match(/\bPosted\s*:\s*(.*?)(?=\s+(?:Size|Seeds?|Peers?|Downloads?)\s*:|$)/i)?.[1]||"").trim().slice(0,160);const name=download.text||anchors.find(item=>item.text&&item.href!==download.href)?.text||"种子下载";items.push({name:name.slice(0,500),posted,downloadUrl});seen.add(downloadUrl)}return items}
export function parseCommentMutationHtml(html:string):GalleryComment[]{const error=cleanText(String(html||"").match(/<p\b[^>]*>([\s\S]*?)<\/p>/i)?.[1]||"");if(error&&/(?:error|must|cannot|not allowed|requires)/i.test(error))throw new Error(error.slice(0,300));return parseComments(html)}
export function parseEditableCommentResponse(raw:string):{id:number;text:string}{let value:any;try{value=JSON.parse(raw)}catch{throw new Error("评论编辑响应无效。")}if(value?.error)throw new Error(String(value.error).slice(0,300));const id=Number(value?.comment_id),text=cleanText(String(value?.editable_comment||"").match(/<textarea\b[^>]*>([\s\S]*?)<\/textarea>/i)?.[1]||"");if(!Number.isInteger(id)||id<=0)throw new Error("评论编辑响应无效。");return{id,text}}
export function parseCommentVoteResponse(raw:string):CommentVoteResult{let value:any;try{value=JSON.parse(raw)}catch{throw new Error("评论投票响应无效。")}if(value?.error)throw new Error(String(value.error).slice(0,300));const id=Number(value?.comment_id),score=Number(value?.comment_score),voted=Number(value?.comment_vote);if(!Number.isInteger(id)||id<=0||!Number.isFinite(score)||![-1,0,1].includes(voted))throw new Error("评论投票响应无效。");return{id,score,voted:voted as -1|0|1}}
export function parseArchiveOptionsHtml(html:string):ArchiveOption[]{const out:ArchiveOption[]=[];for(const match of String(html||"").matchAll(/do_hathdl\(\s*['"]([^'"]+)['"]\s*\)[\s\S]{0,300}?>([^<]+)</gi)){const resolution=match[1],name=cleanText(match[2]);if(name&&!out.some(item=>item.resolution===resolution))out.push({name,resolution,original:/original/i.test(`${resolution} ${name}`)})}return out}
export function parseRatingCredentials(html:string,detailUrl:string):RatingCredentials|null{let url:URL;try{url=new URL(detailUrl)}catch{return null}const ref=url.pathname.match(/^\/g\/(\d+)\/([a-f0-9]+)\/?$/i);const uid=String(html||"").match(/\bapiuid\s*=\s*(-?\d+)/i),key=String(html||"").match(/\bapikey\s*=\s*(["'])([a-f0-9]+)\1/i);if(!ref||!uid||!key)return null;const apiUid=Number(uid[1]);if(!Number.isInteger(apiUid)||apiUid<0)return null;return{gid:Number(ref[1]),token:ref[2],apiUid,apiKey:key[2]}}
export function encodeGalleryRating(rating:number):number|null{if(!Number.isFinite(rating)||rating<0.5||rating>5||!Number.isInteger(rating*2))return null;return Math.ceil(rating*2)}
export function buildGalleryRatingRequest(credentials:RatingCredentials,rating:number){const encoded=encodeGalleryRating(rating);if(encoded==null)throw new Error("评分必须为 0.5 到 5.0 的半星递增值。");return{method:"rategallery",apiuid:credentials.apiUid,apikey:credentials.apiKey,gid:credentials.gid,token:credentials.token,rating:encoded}}
export function parseRatingResponse(raw:string):RatingResult{let value:any;try{value=JSON.parse(raw)}catch{throw new Error("评分响应无效。")}const rating=Number(value?.rating_avg),ratingCount=Number(value?.rating_cnt);if(!Number.isFinite(rating)||!Number.isFinite(ratingCount)||rating<0||ratingCount<0)throw new Error("评分响应无效。");return{rating,ratingCount}}
function parseRelations(html:string,baseUrl:string){const result:Array<{label:string;url:string}>=[],seen=new Set<string>();for(const row of html.match(/<tr\b[^>]*>[\s\S]*?<\/tr>/gi)||[]){const rowHint=cleanText(row);for(const match of row.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){const tag=`<a ${match[1]}>`,href=absoluteUrl(getAttribute(tag,"href"),baseUrl),text=cleanText(match[2]),hint=`${rowHint} ${getAttribute(tag,"title")} ${text} ${getAttribute(tag,"class")}`;if(!/\/g\/\d+\/[a-f0-9]+\/?/i.test(href)||!/(?:parent|newer|older|version|supersed|replaced)/i.test(hint)||seen.has(href))continue;const label=/parent/i.test(hint)?"父画廊":/(?:newer|new version|supersed)/i.test(hint)?"较新版本":/(?:older|old version|replaced)/i.test(hint)?"较早版本":"画廊版本";result.push({label,url:href});seen.add(href)}}for(const match of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){const tag=`<a ${match[1]}>`,href=absoluteUrl(getAttribute(tag,"href"),baseUrl),text=cleanText(match[2]),hint=`${getAttribute(tag,"title")} ${text} ${getAttribute(tag,"class")}`;if(!/\/g\/\d+\/[a-f0-9]+\/?/i.test(href)||!/(?:parent|newer|older|version|supersed|replaced)/i.test(hint)||seen.has(href))continue;const label=/parent/i.test(hint)?"父画廊":/(?:newer|new version|supersed)/i.test(hint)?"较新版本":/(?:older|old version|replaced)/i.test(hint)?"较早版本":"画廊版本";result.push({label,url:href});seen.add(href)}return result.slice(0,4)}
export function parseDetailHtml(html:string,baseUrl:string):DetailExtractData{const body=cleanText(html),title=findElementTextById(html,"gn"),ratingLabel=findElementTextById(html,"rating_label"),ratingMatch=ratingLabel.match(/([0-9]+(?:\.[0-9]+)?)/),ratingCount=Number(findElementTextById(html,"rating_count").replace(/,/g,""))||0,favorite=parseFavoriteInfo(html);return{title,titleJpn:findElementTextById(html,"gj"),cover:parseCover(html,baseUrl),category:parseCategory(html),uploader:findElementTextById(html,"gdn"),rating:ratingMatch?Number(ratingMatch[1]):null,ratingCount,ratingCredentials:parseRatingCredentials(html,baseUrl),metadata:parseMetadata(html),tags:parseTags(html,baseUrl),previewPages:parsePreviewPages(html),pageLinks:parsePreviewPageHtml(html,baseUrl),isFavorited:favorite.isFavorited,favoriteName:favorite.favoriteName,comments:parseComments(html),torrentUrl:findActionUrl(html,baseUrl,"torrent"),archiveUrl:findActionUrl(html,baseUrl,"archive"),relations:parseRelations(html,baseUrl),error:detectPageError(body)||(!title?"没有识别到画廊详情，页面结构可能已变化。":"")}}
