import { GallerySummary } from "./extractors"
import { parseSearchHtml } from "./searchHtml"
import { fetchHtml } from "./ehentai"
import { getBaseUrl, getAccountStatus } from "./account"
import { reportDiagnostic } from "./githubBridge"

export type FavoriteCategory = { index: number; name: string; count: number }
export type FavoriteSearch = { query?: string; searchName?: boolean; searchTags?: boolean; searchNote?: boolean }
export type FavoritesPage = { categories: FavoriteCategory[]; items: GallerySummary[]; resultCount: string; prevHref: string; nextHref: string; url: string }
const clean = (value: string) => String(value || "").replace(/<[^>]+>/g, " ").replace(/&nbsp;/gi, " ").replace(/\s+/g, " ").trim()
export function buildFavoritesUrl(baseUrl: string, category?: number, search: FavoriteSearch = {}): string { const url = new URL("favorites.php", baseUrl); if (category != null) url.searchParams.set("favcat", String(category)); const query = String(search.query || "").trim(); if (query) { url.searchParams.set("f_search", query); url.searchParams.set("sn", search.searchName === false ? "0" : "1"); if (search.searchTags) url.searchParams.set("st", "1"); if (search.searchNote) url.searchParams.set("sf", "1") } return url.toString() }
export function parseFavoriteCategories(html: string): FavoriteCategory[] { const found = new Map<number, FavoriteCategory>(); const matches = [...html.matchAll(/<[^>]*\bclass\s*=\s*(["'])[^"']*\bfp\b[^"']*\1[^>]*>/gi)].map(match => ({ match, slot: (match[0].match(/\bfavcat\s*=\s*([0-9])/i) || [])[1] })).filter(item => /^[0-9]$/.test(String(item.slot))); for (let i = 0; i < matches.length; i += 1) { const { match, slot } = matches[i]; const start = (match.index || 0) + match[0].length; const end = i + 1 < matches.length ? (matches[i + 1].match.index || html.length) : html.length; const text = clean(html.slice(start, end)); const count = Number((text.match(/([\d,]+)/)?.[1] || "0").replace(/,/g, "")) || 0; const name = text.replace(/^\s*[\d,]+\s*/, "").trim() || `收藏夹 ${slot}`; found.set(Number(slot), { index: Number(slot), name, count }) } return Array.from({ length: 10 }, (_, index) => found.get(index) || { index, name: `收藏夹 ${index}`, count: 0 }) }
function validPageUrl(value: string): boolean { try { const url = new URL(value); const base = new URL(getBaseUrl()); return url.origin === base.origin && url.pathname.endsWith("/favorites.php") } catch { return false } }
export function favoriteLoginError(html: string) { return /requires you to log on|not logged in|please log on/i.test(html) ? "收藏需要登录；请刷新账号状态或重新导入 Cookie。" : "" }
async function report(input: Parameters<typeof reportDiagnostic>[0]) { try { await reportDiagnostic(input) } catch {} }
export async function loadFavorites(category?: number, search: FavoriteSearch = {}, directUrl?: string): Promise<FavoritesPage> { if (!getAccountStatus().loggedIn) throw new Error("请先登录后查看收藏。") ; if (category != null && (!Number.isInteger(category) || category < 0 || category > 9)) throw new Error("收藏分类必须为 0 到 9。") ; const url = directUrl && validPageUrl(directUrl) ? directUrl : buildFavoritesUrl(getBaseUrl(), category, search); let response: any; try { const result = await fetchHtml(url, "favorites.list"); response = result.response; const html = result.html; const login = favoriteLoginError(html); if (login) throw new Error(login); const parsed = parseSearchHtml(html, String(response.url || url)); if (parsed.error && !/No hits found/i.test(html)) throw new Error("收藏列表解析失败，请稍后重试。") ; const data = { categories: parseFavoriteCategories(html), items: parsed.items, resultCount: parsed.resultCount, prevHref: parsed.prevHref, nextHref: parsed.nextHref, url: String(response.url || url) }; await report({ stage: "favorites.list", ok: true, request: { url: data.url, status: response.status }, notes: `items=${data.items.length}; categories=${data.categories.length}` }); return data } catch (error) { await report({ stage: "favorites.list", ok: false, error, request: { url, status: Number(response?.status || 0) } }); throw error } }
