import { GallerySummary } from "./extractors"
import { parseSearchHtml } from "./searchHtml"
import { fetchHtml, invalidateGalleryCaches, postForm } from "./ehentai"
import { getBaseUrl, getAccountStatus } from "./account"
import { reportDiagnostic } from "./githubBridge"
import { parseGalleryRef } from "./pure"

export type FavoriteCategory = { index: number; name: string; count: number }
export type FavoriteSearch = { query?: string; searchName?: boolean; searchTags?: boolean; searchNote?: boolean }
export type FavoritesPage = { categories: FavoriteCategory[]; items: GallerySummary[]; resultCount: string; prevHref: string; nextHref: string; url: string }
export type FavoriteState = { category: number | null; note: string; categories: FavoriteCategory[] }
const clean = (value: string) => String(value || "").replace(/<[^>]+>/g, " ").replace(/&nbsp;/gi, " ").replace(/\s+/g, " ").trim()
export function buildFavoritesUrl(baseUrl: string, category?: number, search: FavoriteSearch = {}): string { const url = new URL("favorites.php", baseUrl); if (category != null) url.searchParams.set("favcat", String(category)); const query = String(search.query || "").trim(); if (query) { url.searchParams.set("f_search", query); url.searchParams.set("sn", "on"); url.searchParams.set("st", "on"); url.searchParams.set("sf", "on") } return url.toString() }
export function parseFavoriteCategories(html: string): FavoriteCategory[] { const scope=html.match(/<[^>]*\bclass\s*=\s*(["'])[^"']*\bido\b[^"']*\1[^>]*>[\s\S]*/i)?.[0]||html;const matches=[...scope.matchAll(/<[^>]*\bclass\s*=\s*(["'])[^"']*\bfp\b[^"']*\1[^>]*>/gi)].slice(0,10);return Array.from({length:10},(_,index)=>{const match=matches[index];if(!match)return{index,name:`收藏夹 ${index}`,count:0};const start=(match.index||0)+match[0].length,end=index+1<matches.length?(matches[index+1].index||scope.length):scope.length,segment=scope.slice(start,end),fields=[...segment.matchAll(/<div\b[^>]*>([\s\S]*?)<\/div>/gi)].map(value=>clean(value[1]));const count=Number(String(fields[0]||"0").replace(/[^\d,]/g,"").replace(/,/g,""))||0,name=String(fields[2]||"").trim()||`收藏夹 ${index}`;return{index,name,count}}) }
export function parseFavoriteState(metadata: Record<string, string>): FavoriteState { const value = String(metadata.Favorited || metadata.favorited || ""); const category = Number(value.match(/(?:category|favcat)\s*(\d)/i)?.[1]); return { category: Number.isInteger(category) && category >= 0 && category <= 9 ? category : null, note: "", categories:[] } }
export function parseFavoritePopupHtml(html:string):FavoriteState{const options=[...String(html||"").matchAll(/<option\b([^>]*)>([\s\S]*?)<\/option>/gi)].map(match=>{const attrs=String(match[1]||""),index=Number(attrs.match(/\bvalue\s*=\s*(["']?)([0-9])\1/i)?.[2]),name=clean(match[2]);return Number.isInteger(index)&&index>=0&&index<=9?{index,name:name||`收藏夹 ${index}`,count:0}:null}).filter(Boolean) as FavoriteCategory[],selected=String(html||"").match(/<option\b[^>]*\bvalue\s*=\s*(["']?)([0-9])\1[^>]*\bselected\b[^>]*>/i)||String(html||"").match(/<option\b[^>]*\bselected\b[^>]*\bvalue\s*=\s*(["']?)([0-9])\1[^>]*>/i),category=Number(selected?.[2]),input=String(html||"").match(/<input\b[^>]*\bname\s*=\s*(["'])favnote\1[^>]*>/i)?.[0]||"",note=(input.match(/\bvalue\s*=\s*(["'])(.*?)\1/i)?.[2]||"").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&amp;/gi,"&").trim().slice(0,200);return{category:Number.isInteger(category)&&category>=0&&category<=9?category:null,note,categories:Array.from({length:10},(_,index)=>options.find(item=>item.index===index)||{index,name:`收藏夹 ${index}`,count:0})}}
function validPageUrl(value: string): boolean { try { const url = new URL(value); const base = new URL(getBaseUrl()); return url.origin === base.origin && url.pathname.endsWith("/favorites.php") } catch { return false } }
export function favoriteLoginError(html: string) { return /requires you to log on|not logged in|please log on/i.test(html) ? "收藏需要登录；请刷新账号状态或重新导入 Cookie。" : "" }
async function report(input: Parameters<typeof reportDiagnostic>[0]) { try { await reportDiagnostic(input) } catch {} }
export async function loadFavorites(category?: number, search: FavoriteSearch = {}, directUrl?: string): Promise<FavoritesPage> { if (!getAccountStatus().loggedIn) throw new Error("请先登录后查看收藏。"); if (category != null && (!Number.isInteger(category) || category < 0 || category > 9)) throw new Error("收藏分类必须为 0 到 9。"); const url = directUrl && validPageUrl(directUrl) ? directUrl : buildFavoritesUrl(getBaseUrl(), category, search); let response: any; try { const result = await fetchHtml(url, "favorites.list"); response = result.response; const login = favoriteLoginError(result.html); if (login) throw new Error(login); const parsed = parseSearchHtml(result.html, result.finalUrl),hasGalleryRows=/\bclass\s*=\s*(["'])[^"']*\bitg\b[^"']*\1/i.test(result.html)&&/\/g\/\d+\/[a-f0-9]+/i.test(result.html); if ((parsed.error || hasGalleryRows&&!parsed.items.length) && !/No hits found/i.test(result.html)) throw new Error("收藏列表解析失败，请稍后重试。"); const data = { categories: parseFavoriteCategories(result.html), items: parsed.items, resultCount: parsed.resultCount, prevHref: parsed.prevHref, nextHref: parsed.nextHref, url: result.finalUrl }; await report({ stage: "favorites.list", ok: true, request: { url: data.url, status: response.status }, notes: `items=${data.items.length}; categories=${data.categories.length}` }); return data } catch (error) { await report({ stage: "favorites.list", ok: false, error, request: { url, status: Number(response?.status || 0) } }); throw error } }
export async function loadFavoriteState(item: GallerySummary): Promise<FavoriteState> { if (!getAccountStatus().loggedIn) throw new Error("请先登录后查看收藏备注。"); const ref=parseGalleryRef(item.url);if(!ref)throw new Error("画廊身份无效，无法读取收藏备注。");const url=new URL("gallerypopups.php",getBaseUrl());url.searchParams.set("gid",ref.gid);url.searchParams.set("t",ref.token);url.searchParams.set("act","addfav");const result=await fetchHtml(url.toString(),"favorites.read");const login=favoriteLoginError(result.html);if(login)throw new Error(login);return parseFavoritePopupHtml(result.html) }
export function verifyFavoriteMutationFromState(state:FavoriteState,category:number|null,note=""){if(state.category!==category)throw new Error("收藏操作未被服务器确认，请稍后刷新后重试。");if(category!=null&&String(note||"").trim()&&state.note!==String(note||"").trim().slice(0,200))throw new Error("收藏备注未被服务器确认，请稍后刷新后重试。");return state}
export function verifyFavoriteMutation(html:string,category:number|null,note=""){const login=favoriteLoginError(html);if(login)throw new Error(login);return verifyFavoriteMutationFromState(parseFavoritePopupHtml(html),category,note)}
export async function changeFavorite(item: GallerySummary, category: number | null, note = ""): Promise<FavoriteState> { if (!getAccountStatus().loggedIn) throw new Error("请先登录后管理收藏。"); if (category != null && (!Number.isInteger(category) || category < 0 || category > 9)) throw new Error("收藏分类必须为 0 到 9。"); const ref = parseGalleryRef(item.url); if (!ref) throw new Error("画廊身份无效，无法管理收藏。"); const url = new URL("gallerypopups.php", getBaseUrl()); url.searchParams.set("gid", ref.gid); url.searchParams.set("t", ref.token); url.searchParams.set("act", "addfav"); const result = await postForm(url.toString(), { favcat: category == null ? "favdel" : String(category), favnote: String(note || "").slice(0, 200), submit: "Apply Changes", update: "1" }, "favorites.change"); const login=favoriteLoginError(result.html);if(login)throw new Error(login); const verified=verifyFavoriteMutationFromState(await loadFavoriteState(item),category,note); invalidateGalleryCaches(); await report({ stage: "favorites.change", ok: true, request: { url: result.finalUrl, status: Number(result.response.status || 0) }, notes: `operation=${category == null ? "remove" : "set"}` });return verified }
