import { Button, Device, GlassEffectContainer, HStack, Image, NavigationLink, Rectangle, Text, VStack, ZStack } from "scripting"

const shape={type:"rect" as const,cornerRadius:16,style:"continuous" as const}
const actionShape={type:"rect" as const,cornerRadius:12,style:"continuous" as const}
export function supportsLiquidGlass(systemVersion=Device.systemVersion){return Number(String(systemVersion||"0").split(".")[0])>=26}
export function PageBackground(){return <Rectangle fill={{colors:["#F1ECFA","#DED7F0"],startPoint:"topLeading",endPoint:"bottomTrailing"}} ignoresSafeArea allowsHitTesting={false}/>} 
export function GlassSurface({children,padding=14,actionGroup=false}:{children?:any;padding?:number;actionGroup?:boolean}){const content=<ZStack frame={{maxWidth:"infinity"}} padding={padding} background={supportsLiquidGlass()?undefined:{style:"thinMaterial",shape}} glassEffect={supportsLiquidGlass()?{glass:UIGlass.regular().interactive(false),shape}:undefined} clipShape={shape} shadow={supportsLiquidGlass()?undefined:{color:"rgba(82,66,120,0.18)",radius:12,y:5}}>{children}</ZStack>;return actionGroup&&supportsLiquidGlass()?<GlassEffectContainer spacing={10}>{content}</GlassEffectContainer>:content}
export function GlassActionGroup({children,spacing=10}:{children:any;spacing?:number}){return supportsLiquidGlass()?<GlassEffectContainer spacing={spacing}>{children}</GlassEffectContainer>:<VStack alignment="leading" spacing={spacing} frame={{maxWidth:"infinity"}}>{children}</VStack>}
export function GlassActionButton({title,systemImage,disabled=false,action,destination,emphasized=false,fullWidth=true}:{title:string;systemImage?:string;disabled?:boolean;action?:()=>void;destination?:any;emphasized?:boolean;fullWidth?:boolean}){const content=<HStack spacing={6} padding={{horizontal:12,vertical:10}} frame={{maxWidth:fullWidth?"infinity":undefined,minHeight:44,alignment:"center"}}>{systemImage?<Image systemName={systemImage}/>:null}<Text font="subheadline" fontWeight="semibold">{title}</Text></HStack>;if(supportsLiquidGlass())return destination!==undefined?<NavigationLink destination={destination} disabled={disabled} buttonStyle={emphasized?"glassProminent":"glass"}>{content}</NavigationLink>:<Button buttonStyle={emphasized?"glassProminent":"glass"} disabled={disabled} action={action||(()=>{})} frame={{maxWidth:fullWidth?"infinity":undefined}}>{content}</Button>;const framed=<ZStack frame={{maxWidth:fullWidth?"infinity":undefined}} background={emphasized?"accentColor":{style:"thinMaterial",shape:actionShape}} clipShape={actionShape} shadow={{color:"rgba(82,66,120,0.16)",radius:8,y:3}}>{content}</ZStack>;return destination!==undefined?<NavigationLink destination={destination} disabled={disabled}>{framed}</NavigationLink>:<Button buttonStyle="plain" disabled={disabled} action={action||(()=>{})} frame={{maxWidth:fullWidth?"infinity":undefined}}>{framed}</Button>}
export function ShelfHeader({title,caption}:{title:string;caption?:string}){return <HStack spacing={9} padding={{top:4,bottom:3}} frame={{maxWidth:"infinity",alignment:"leading"}}><Rectangle fill="accentColor" frame={{width:4,height:20}} clipShape="capsule"/><VStack alignment="leading" spacing={1}><Text font="headline" fontWeight="semibold">{title}</Text>{caption?<Text font="caption" foregroundStyle="secondaryLabel">{caption}</Text>:null}</VStack></HStack>}
