import { Button, Device, GlassEffectContainer, HStack, Image, NavigationLink, Rectangle, Text, TextField, VStack, ZStack } from "scripting"

export const AppUI={spacing:{xs:4,sm:8,md:12,lg:16,xl:20},radius:{control:10,card:14,hero:18},galleryCardHeight:338,galleryCoverHeight:190}
const cardShape={type:"rect" as const,cornerRadius:AppUI.radius.card,style:"continuous" as const}
const actionShape={type:"rect" as const,cornerRadius:AppUI.radius.control,style:"continuous" as const}
export function supportsLiquidGlass(systemVersion=Device.systemVersion){return Number(String(systemVersion||"0").split(".")[0])>=26}
export function PageBackground(){return <Rectangle fill="systemGroupedBackground" ignoresSafeArea allowsHitTesting={false}/>}
export function GlassSurface({children,padding=14,actionGroup=false,floating=false}:{children?:any;padding?:number;actionGroup?:boolean;floating?:boolean}){const liquid=supportsLiquidGlass()&&(floating||actionGroup),content=<VStack alignment="leading" spacing={0} padding={padding} frame={{maxWidth:"infinity",alignment:"leading"}} background={liquid?undefined:floating?{style:"thinMaterial",shape:cardShape}:"secondarySystemGroupedBackground"} glassEffect={liquid?{glass:UIGlass.regular().interactive(floating),shape:cardShape}:undefined} clipShape={cardShape}>{children}</VStack>;return actionGroup&&supportsLiquidGlass()?<GlassEffectContainer spacing={AppUI.spacing.sm}>{content}</GlassEffectContainer>:content}
export function GlassActionGroup({children,spacing=AppUI.spacing.sm}:{children:any;spacing?:number}){return supportsLiquidGlass()?<GlassEffectContainer spacing={spacing}>{children}</GlassEffectContainer>:<VStack alignment="leading" spacing={spacing} frame={{maxWidth:"infinity"}}>{children}</VStack>}
export function GlassActionButton({title,subtitle,systemImage,disabled=false,action,destination,emphasized=false,fullWidth=true,compact=false}:{title:string;subtitle?:string;systemImage?:string;disabled?:boolean;action?:()=>void;destination?:any;emphasized?:boolean;fullWidth?:boolean;compact?:boolean}){const content=<HStack spacing={8} padding={{horizontal:compact?8:12,vertical:compact?0:8}} frame={{maxWidth:fullWidth?"infinity":undefined,minHeight:44,alignment:"center"}}>{systemImage?<Image systemName={systemImage}/>:null}<VStack alignment={subtitle?"leading":"center"} spacing={1} frame={{maxWidth:subtitle?"infinity":undefined,alignment:subtitle?"leading":"center"}}><Text font="subheadline" fontWeight="semibold" lineLimit={1}>{title}</Text>{subtitle?<Text font="caption" foregroundStyle="secondaryLabel" lineLimit={1}>{subtitle}</Text>:null}</VStack></HStack>;if(supportsLiquidGlass())return destination!==undefined?<NavigationLink destination={destination} disabled={disabled} buttonStyle={emphasized?"glassProminent":"glass"}>{content}</NavigationLink>:<Button buttonStyle={emphasized?"glassProminent":"glass"} disabled={disabled} action={action||(()=>{})} frame={{maxWidth:fullWidth?"infinity":undefined}}>{content}</Button>;const framed=<ZStack frame={{maxWidth:fullWidth?"infinity":undefined}} background={emphasized?"accentColor":"tertiarySystemFill"} clipShape={actionShape}>{content}</ZStack>;return destination!==undefined?<NavigationLink destination={destination} disabled={disabled}>{framed}</NavigationLink>:<Button buttonStyle="plain" disabled={disabled} action={action||(()=>{})} frame={{maxWidth:fullWidth?"infinity":undefined}}>{framed}</Button>}
export function ShelfHeader({title,caption,action}:{title:string;caption?:string;action?:any}){return <HStack alignment="center" spacing={AppUI.spacing.sm} padding={{top:2,bottom:2}} frame={{maxWidth:"infinity",alignment:"leading"}}><VStack alignment="leading" spacing={2} frame={{maxWidth:"infinity",alignment:"leading"}}><Text font="headline" fontWeight="semibold">{title}</Text>{caption?<Text font="caption" foregroundStyle="secondaryLabel">{caption}</Text>:null}</VStack>{action||null}</HStack>}
export function NativeSearchBar({value,onChanged,prompt,onSubmit,submitTitle="搜索",disabled=false}:{value:string;onChanged:(value:string)=>void;prompt:string;onSubmit:()=>void;submitTitle?:string;disabled?:boolean}){return <HStack spacing={8} alignment="center" frame={{maxWidth:"infinity"}}><HStack spacing={6} padding={{horizontal:10,vertical:6}} frame={{maxWidth:"infinity",minHeight:36,alignment:"leading"}} background="tertiarySystemFill" clipShape={{type:"rect",cornerRadius:AppUI.radius.control,style:"continuous"}}><Image systemName="magnifyingglass" foregroundStyle="secondaryLabel"/><TextField title={prompt} value={value} onChanged={onChanged} prompt={prompt} submitLabel="search" onSubmit={{triggers:"text",action:onSubmit}} textFieldStyle="plain" keyboardType="webSearch" labelsHidden frame={{maxWidth:"infinity"}}/></HStack><Button title={submitTitle} buttonStyle="borderedProminent" disabled={disabled} action={onSubmit}/></HStack>}
export function SettingsRowLabel({title,subtitle,systemImage}:{title:string;subtitle?:string;systemImage:string}){return <HStack spacing={AppUI.spacing.md} frame={{maxWidth:"infinity",alignment:"leading"}}><Image systemName={systemImage} foregroundStyle="accentColor" frame={{width:24}}/><VStack alignment="leading" spacing={2} frame={{maxWidth:"infinity",alignment:"leading"}}><Text>{title}</Text>{subtitle?<Text font="caption" foregroundStyle="secondaryLabel">{subtitle}</Text>:null}</VStack></HStack>}
export function NativeCard({children,padding=12}:{children:any;padding?:number}){return <VStack alignment="leading" spacing={0} padding={padding} frame={{maxWidth:"infinity",alignment:"leading"}} background="secondarySystemGroupedBackground" clipShape={cardShape}>{children}</VStack>}
