export type PerformanceRecord={id:number;page:number;host:string;urlHash:string;mode:"reading"|"test";concurrency:number;foreground:boolean;prefetch:boolean;cacheHit:boolean;reusedPromise:boolean;networkStarted:boolean;aborted:boolean;failed:boolean;activeRequests:number;queueMs:number;resolveImagePageMs:number;responseAvailableMs:number|null;firstChunkObservedMs:number|null;dnsMs:null;connectMs:null;ttfbMs:null;downloadMs:number;totalMs:number;cacheReadMs:number;cacheWriteMs:number;bytes:number;mbps:number}
export function performanceUrlIdentity(url:string){let host="unknown";try{host=new URL(url).hostname.toLowerCase();if(!/^[a-z0-9.-]{1,253}$/.test(host))host="unknown"}catch{};let a=2166136261,b=2246822519;for(let i=0;i<url.length;i++){a=Math.imul(a^url.charCodeAt(i),16777619);b=Math.imul(b^url.charCodeAt(i),3266489917)}return{host,urlHash:(a>>>0).toString(16).padStart(8,"0")+(b>>>0).toString(16).padStart(8,"0")}}
let sequence=0,capturing=false
const recent:PerformanceRecord[]=[]
export function performanceCaptureEnabled(){return capturing}
export function setPerformanceCapture(enabled:boolean){capturing=enabled}
export function performanceSnapshot(){return recent.map(item=>({...item}))}
export function startPerformanceRecord(url:string,meta:{page?:number;resolveMs?:number;foreground?:boolean;prefetch?:boolean;testConcurrency?:number}={}){if(!capturing&&!meta.testConcurrency)return null;const start=Date.now(),identity=performanceUrlIdentity(url);const record:PerformanceRecord={id:++sequence,page:Math.max(0,Math.trunc(meta.page||0)),...identity,mode:meta.testConcurrency?"test":"reading",concurrency:meta.testConcurrency||0,foreground:Boolean(meta.foreground),prefetch:Boolean(meta.prefetch),cacheHit:false,reusedPromise:false,networkStarted:false,aborted:false,failed:false,activeRequests:0,queueMs:0,resolveImagePageMs:Math.max(0,meta.resolveMs||0),responseAvailableMs:null,firstChunkObservedMs:null,dnsMs:null,connectMs:null,ttfbMs:null,downloadMs:0,totalMs:0,cacheReadMs:0,cacheWriteMs:0,bytes:0,mbps:0};let finished=false;return {record,finish:()=>{if(finished)return;finished=true;record.totalMs=Date.now()-start+record.resolveImagePageMs;record.mbps=record.networkStarted&&record.downloadMs>0?record.bytes/1e6/(record.downloadMs/1000):0;recent.push({...record});if(recent.length>320)recent.shift()}}}
const mean=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0
export function percentile(values:number[],q:number){const sorted=[...values].sort((a,b)=>a-b);return sorted.length?sorted[Math.max(0,Math.ceil(q*sorted.length)-1)]:0}
export function summarizePerformance(records:PerformanceRecord[],elapsedMs:number){const network=records.filter(r=>r.networkStarted&&!r.failed&&!r.aborted&&!r.cacheHit&&!r.reusedPromise),hosts:Record<string,{count:number;averageMBps:number}>={};for(const host of new Set(network.map(r=>r.host))){const values=network.filter(r=>r.host===host);hosts[host]={count:values.length,averageMBps:mean(values.map(r=>r.mbps))}}const byUrl=new Map<string,number>();for(const r of records.filter(r=>r.networkStarted))byUrl.set(r.urlHash,(byUrl.get(r.urlHash)||0)+1);return{requests:records.length,networkSamples:network.length,averageMBps:mean(network.map(r=>r.mbps)),medianMBps:percentile(network.map(r=>r.mbps),0.5),p90DownloadMs:percentile(network.map(r=>r.downloadMs),0.9),averageResolveMs:mean(records.map(r=>r.resolveImagePageMs)),averageQueueMs:mean(records.map(r=>r.queueMs)),throughputMBps:elapsedMs>0?network.reduce((sum,r)=>sum+r.bytes,0)/1e6/(elapsedMs/1000):0,averageBytes:mean(network.map(r=>r.bytes)),cacheHitRate:records.length?records.filter(r=>r.cacheHit).length/records.length:0,aborts:records.filter(r=>r.aborted).length,failures:records.filter(r=>r.failed).length,promiseReuses:records.filter(r=>r.reusedPromise).length,duplicateRequests:[...byUrl.values()].reduce((sum,count)=>sum+Math.max(0,count-1),0),hosts}}
export type PerformanceGroup={concurrency:number;elapsedMs:number;records:PerformanceRecord[];interfered?:boolean}
export function performanceRecommendation(groups:PerformanceGroup[]){const valid=groups.filter(group=>!group.interfered).map(group=>({c:group.concurrency,s:summarizePerformance(group.records,group.elapsedMs)})).filter(g=>g.s.networkSamples===8&&g.s.requests===8&&!g.s.aborts&&!g.s.failures&&g.s.cacheHitRate===0);if(valid.length!==5||![1,2,3,4,6].every(c=>valid.some(group=>group.c===c)))return "样本不足或存在失败/缓存干扰：不推荐修改并发、预载或主机限制。";const best=Math.max(...valid.map(g=>g.s.throughputMBps)),choice=valid.filter(g=>g.s.throughputMBps>=best*0.9).sort((a,b)=>a.c-b.c)[0];const baseline=valid.find(g=>g.c===1)!;const latencyFactor=choice.s.p90DownloadMs/Math.max(1,baseline.s.p90DownloadMs);const hostRecommendations:string[]=[];for(const host of new Set(groups.flatMap(group=>group.records.map(r=>r.host)))){const hostGroups=groups.map(group=>({c:group.concurrency,s:summarizePerformance(group.records.filter(r=>r.host===host),group.elapsedMs)}));if(hostGroups.every(g=>g.s.networkSamples>=5)){const peak=Math.max(...hostGroups.map(g=>g.s.throughputMBps)),candidate=hostGroups.filter(g=>g.s.throughputMBps>=peak*0.9).sort((a,b)=>a.c-b.c)[0];hostRecommendations.push(`${host}：候选${candidate.c}（仅下载实验）`)}else hostRecommendations.push(`${host}：样本不足，保持原值`)}
return `候选图片并发：${choice.c}（达到最佳总吞吐90%的最小并发）。\n候选prefetch concurrency：${Math.max(1,choice.c-1)}（为当前页预留一路；需混合前台/预取再验证）。\nreader current image priority：保持当前页高于预取；纯下载实验不能推导数值优先级。\npreload window：暂不推荐修改；需实际翻页间隔及缓存命中数据，纯下载不能推导。\nper-host concurrency：${hostRecommendations.join("；")}。\n候选组P90相对并发1：${latencyFactor.toFixed(2)}倍；未自动应用任何设置。`}
export function performanceTextReport(groups:PerformanceGroup[],reading:PerformanceRecord[]=[]){const lines=["Reader 图片性能诊断 · 本机脱敏报告","MB/s使用十进制MB；速度=字节/从fetch调用至body结束耗时。","DNS/连接/精确TTFB：API不可获得。responseAvailable/firstChunk为JS观测值，含缓冲与调度。","测试：绕过应用缓存，HTTP请求no-cache/no-store；无法确认原生/代理缓存来源。","相同页面的跨组重复下载是实验设计，重复请求数只在组内计。","每组顺序执行，固定并发池；结论有节点/时间漂移与样本量限制。", "resolve均值来自测试前统一准备，不在组吞吐耗时中；totalMs逐请求含该准备耗时。"]
for(const group of groups){const s=summarizePerformance(group.records,group.elapsedMs);lines.push(`\n并发 ${group.concurrency}${group.interfered?"（受其他请求干扰，不用于推荐）":""}：成功网络样本 ${s.networkSamples}/${s.requests}；平均 ${s.averageMBps.toFixed(3)} MB/s；中位数 ${s.medianMBps.toFixed(3)}；P90下载 ${s.p90DownloadMs.toFixed(0)}ms；resolve均值 ${s.averageResolveMs.toFixed(0)}ms；queue均值 ${s.averageQueueMs.toFixed(0)}ms；总吞吐 ${s.throughputMBps.toFixed(3)} MB/s；缓存 ${(s.cacheHitRate*100).toFixed(1)}%；abort ${s.aborts}；失败 ${s.failures}；重复 ${s.duplicateRequests}；Promise复用 ${s.promiseReuses}`);for(const [host,value] of Object.entries(s.hosts))lines.push(`host ${host}：${value.averageMBps.toFixed(3)} MB/s（n=${value.count}）`)}
lines.push("\n建议（仅建议）",performanceRecommendation(groups),"\n逐请求JSON（无URL、标题、Cookie、路径）",JSON.stringify(groups.flatMap(group=>group.records)));if(reading.length){const summary=summarizePerformance(reading,0);lines.push("\n阅读采样汇总（未测连续时间段，总吞吐不可用）",JSON.stringify(summary),`瓶颈线索：平均排队 ${summary.averageQueueMs.toFixed(0)}ms / 解析 ${summary.averageResolveMs.toFixed(0)}ms / P90下载 ${summary.p90DownloadMs.toFixed(0)}ms；abort ${summary.aborts} / 重复网络 ${summary.duplicateRequests}。节点问题仅能按host相关性判断，不能排除代理/链路。`,JSON.stringify(reading));}return lines.join("\n")}
