import { Script } from "scripting"
import type { GallerySummary } from "./extractors"
import { parseGalleryRef } from "./pure"
import { getBaseUrl, getCookieHeader } from "./account"
import { assertCompletePreviewInventory, loadGalleryDetail, resolveImagePage } from "./ehentai"
export type HistoryRecordV1={gid:string;token:string;site:"e"|"ex";title:string;thumb?:string;category?:string;uploader?:string;pages?:number;lastPageIndex?:number;viewedAt:number;updatedAt:number}
type Db={schemaVersion:1;history:HistoryRecordV1[]};export type HistoryStore={read():Promise<string|null>;write(value:string):Promise<void>;readBackup?():Promise<string|null>}
export type ReaderPreferences={version:1;layout:"single"|"continuous";preload:number;preferOriginal:boolean}
export type SavedSearch={id:string;title:string;query:string;createdAt:number}
export type PreferenceStore={read():Promise<string|null>;write(value:string):Promise<void>}
const fm:any=(globalThis as any).FileManager,MAX=200,DEFAULT_PREFERENCES:ReaderPreferences={version:1,layout:"single",preload:2,preferOriginal:false};let historyQueue:Promise<void>=Promise.resolve(),bookmarkQueue:Promise<void>=Promise.resolve(),searchQueue:Promise<void>=Promise.resolve()
function path(name:string){return `${String(fm?.documentsDirectory||"")}/ehentai-library/${name}`}
async function replaceFile(target:string,value:string){const temp=`${target}.tmp`,backup=`${target}.bak`;await fm.createDirectory(target.split("/").slice(0,-1).join("/"),true);await fm.writeAsString(temp,value);const hadOld=await fm.exists(target);try{if(hadOld){try{if(await fm.exists(backup))await fm.remove(backup)}catch{}await fm.rename(target,backup)}await fm.rename(temp,target);if(hadOld){try{await fm.remove(backup)}catch{}}}catch(error){try{if(!(await fm.exists(target))&&await fm.exists(backup))await fm.rename(backup,target)}catch{};throw error}}
function fileStore(name:string,label:string):HistoryStore{const p=path(name);return{async read(){try{const backup=`${p}.bak`;if(!(await fm.exists(p))&&await fm.exists(backup))await fm.rename(backup,p);return await fm.exists(p)?await fm.readAsString(p):null}catch{throw new Error(`${label}读取失败；原文件未被覆盖。`)}},async readBackup(){try{const backup=`${p}.bak`;return await fm.exists(backup)?await fm.readAsString(backup):null}catch{return null}},async write(value){await replaceFile(p,value)}}}
function store():HistoryStore{return fileStore("history-v1.json","本地历史数据")}
function parseHistory(raw:string|null):Db{if(!raw)return{schemaVersion:1,history:[]};const x=JSON.parse(raw);if(x?.schemaVersion!==1||!Array.isArray(x.history))throw new Error("本地历史数据无法读取；原文件未被覆盖。");return{schemaVersion:1,history:x.history.filter((r:any)=>r&&/^\d+$/.test(r.gid)&&/^[a-f0-9]+$/i.test(r.token)).map((r:any)=>({...r,site:r.site==="ex"?"ex":"e"}))}}
async function loadRecovered<T>(s:HistoryStore,parse:(raw:string|null)=>T,label:string):Promise<T>{const raw=await s.read();try{return parse(raw)}catch(error){const backup=await s.readBackup?.();if(backup==null)throw error;let recovered:T;try{recovered=parse(backup)}catch{throw error}await s.write(backup);return recovered}}
export async function loadHistory(s:HistoryStore=store()){return (await loadRecovered(s,parseHistory,"本地历史数据")).history.sort((a,b)=>b.updatedAt-a.updatedAt)}
async function saveHistory(history:HistoryRecordV1[],s:HistoryStore){await s.write(JSON.stringify({schemaVersion:1,history:history.slice(0,MAX)}))}
function serial<T>(work:()=>Promise<T>):Promise<T>{const next=historyQueue.then(work,work);historyQueue=next.then(()=>undefined,()=>undefined);return next}
function makeRecord(item:GallerySummary,old:HistoryRecordV1|undefined):HistoryRecordV1|null{const ref=parseGalleryRef(item.url);if(!ref)return null;const now=Date.now(),site=new URL(item.url).hostname==="exhentai.org"?"ex":"e" as const;return{gid:ref.gid,token:ref.token,site,title:item.title,thumb:item.thumb,category:item.category,uploader:item.uploader,pages:item.pages,lastPageIndex:old?.lastPageIndex,viewedAt:old?.viewedAt||now,updatedAt:now}}
export async function recordHistory(item:GallerySummary,s:HistoryStore=store()){return serial(async()=>{const h=await loadHistory(s),old=h.find(x=>x.gid===item.gid&&x.token===item.token),record=makeRecord(item,old);if(!record)return;await saveHistory([record,...h.filter(x=>x.gid!==record.gid||x.token!==record.token)],s)})}
export async function updateReadingProgress(item:GallerySummary,index:number,s:HistoryStore=store()){if(!Number.isInteger(index)||index<0)return;return serial(async()=>{const h=await loadHistory(s),old=h.find(x=>x.gid===item.gid&&x.token===item.token),record=makeRecord(item,old);if(!record)return;const bounded=record.pages&&index>=record.pages?record.pages-1:index;record.lastPageIndex=Math.max(old?.lastPageIndex??-1,bounded);await saveHistory([record,...h.filter(x=>x.gid!==record.gid||x.token!==record.token)],s)})}
export function resumeIndex(r:Pick<HistoryRecordV1,"lastPageIndex"|"pages">,count:number){const x=Number(r.lastPageIndex);return Number.isInteger(x)&&x>=0&&x<count&&(!r.pages||x<r.pages)?x:null}
export function historySummary(r:HistoryRecordV1):GallerySummary{const base=getBaseUrl(r.site);return{id:`${r.gid}:${r.token}`,gid:r.gid,token:r.token,title:r.title,category:r.category||"",thumb:r.thumb||"",posted:"",uploader:r.uploader||"",pages:r.pages||0,url:new URL(`g/${r.gid}/${r.token}/`,base).toString()}}
export async function resetReadingProgress(gid:string,token:string,s:HistoryStore=store()){return serial(async()=>{const h=await loadHistory(s),r=h.find(x=>x.gid===gid&&x.token===token);if(!r)return;r.lastPageIndex=undefined;r.updatedAt=Date.now();await saveHistory(h,s)})}
export async function deleteHistory(gid:string,token:string,s:HistoryStore=store()){return serial(async()=>saveHistory((await loadHistory(s)).filter(x=>x.gid!==gid||x.token!==token),s))}
export async function clearHistory(s:HistoryStore=store()){return serial(async()=>saveHistory([],s))}
function normalizePreferences(raw:any):ReaderPreferences{return{version:1,layout:raw?.layout==="continuous"?"continuous":"single",preload:Math.max(0,Math.min(4,Number.isInteger(raw?.preload)?raw.preload:DEFAULT_PREFERENCES.preload)),preferOriginal:Boolean(raw?.preferOriginal)}}
function preferenceStore():PreferenceStore{return fileStore("preferences-v1.json","设置")}
export async function loadPreferences(s:PreferenceStore=preferenceStore()):Promise<ReaderPreferences>{try{return normalizePreferences(await loadRecovered(s,raw=>raw?JSON.parse(raw):DEFAULT_PREFERENCES,"设置"))}catch{throw new Error("设置数据无法读取；原文件未被覆盖。")}}
export async function savePreferences(update:Partial<ReaderPreferences>,s:PreferenceStore=preferenceStore()){const next=normalizePreferences({...await loadPreferences(s),...update});await s.write(JSON.stringify(next));return next}
type SearchDb={schemaVersion:1;items:SavedSearch[]}
function searchStore():PreferenceStore{return fileStore("quick-search-v1.json","快速搜索")}
export async function loadSavedSearches(s:PreferenceStore=searchStore()):Promise<SavedSearch[]>{try{const x:SearchDb=await loadRecovered(s,raw=>{if(!raw)return{schemaVersion:1,items:[]};const value=JSON.parse(raw);if(value?.schemaVersion!==1||!Array.isArray(value.items))throw new Error();return value},"快速搜索");return x.items.filter(i=>i&&typeof i.id==="string"&&typeof i.query==="string").sort((a,b)=>b.createdAt-a.createdAt).slice(0,30)}catch{throw new Error("快速搜索数据无法读取；原文件未被覆盖。")}}
function serialSearch<T>(work:()=>Promise<T>):Promise<T>{const next=searchQueue.then(work,work);searchQueue=next.then(()=>undefined,()=>undefined);return next}
export async function saveSearch(query:string,title=query,s:PreferenceStore=searchStore()){const value=String(query||"").trim();if(!value)throw new Error("搜索词不能为空。");return serialSearch(async()=>{const items=await loadSavedSearches(s),entry:SavedSearch={id:`saved_${Date.now().toString(36)}`,title:String(title||value).trim().slice(0,80)||value,query:value.slice(0,200),createdAt:Date.now()};await s.write(JSON.stringify({schemaVersion:1,items:[entry,...items.filter(i=>i.query!==entry.query)].slice(0,30)}));return entry})}
export async function deleteSavedSearch(id:string,s:PreferenceStore=searchStore()){return serialSearch(async()=>{const items=await loadSavedSearches(s);await s.write(JSON.stringify({schemaVersion:1,items:items.filter(i=>i.id!==id)}))})}

export type LocalBookmarkV1={gid:string;token:string;site:"e"|"ex";title:string;thumb?:string;category?:string;uploader?:string;pages?:number;createdAt:number;updatedAt:number}
type BookmarkDb={schemaVersion:1;items:LocalBookmarkV1[]}
type BookmarkStore=PreferenceStore
function bookmarkStore():BookmarkStore{return fileStore("local-bookmarks-v1.json","本地书签")}
function validBookmark(value:any):value is LocalBookmarkV1{return Boolean(value)&&/^\d+$/.test(String(value.gid||""))&&/^[a-f0-9]+$/i.test(String(value.token||""))&&typeof value.title==="string"&&(value.site==="e"||value.site==="ex")&&Number.isFinite(value.createdAt)&&Number.isFinite(value.updatedAt)}
function parseBookmarks(raw:string|null):BookmarkDb{if(!raw)return{schemaVersion:1,items:[]};const value=JSON.parse(raw);if(value?.schemaVersion!==1||!Array.isArray(value.items)||!value.items.every(validBookmark))throw new Error("本地书签数据无法读取；原文件未被覆盖。");return{schemaVersion:1,items:value.items.map(item=>({...item}))}}
export async function loadLocalBookmarks(s:BookmarkStore=bookmarkStore()){try{return parseBookmarks(await s.read()).items.sort((a,b)=>b.updatedAt-a.updatedAt)}catch{throw new Error("本地书签数据无法读取；原文件未被覆盖。")}}
async function saveLocalBookmarks(items:LocalBookmarkV1[],s:BookmarkStore){await s.write(JSON.stringify({schemaVersion:1,items:items.slice(0,MAX)}))}
function serialBookmark<T>(work:()=>Promise<T>):Promise<T>{const next=bookmarkQueue.then(work,work);bookmarkQueue=next.then(()=>undefined,()=>undefined);return next}
function makeBookmark(item:GallerySummary,old?:LocalBookmarkV1):LocalBookmarkV1{const ref=parseGalleryRef(item.url);if(!ref)throw new Error("画廊身份无效。");const now=Date.now(),site=new URL(item.url).hostname==="exhentai.org"?"ex":"e" as const;return{gid:ref.gid,token:ref.token,site,title:String(item.title||"未命名画廊").slice(0,500),thumb:String(item.thumb||""),category:String(item.category||""),uploader:String(item.uploader||""),pages:Number(item.pages||0),createdAt:old?.createdAt||now,updatedAt:now}}
export async function addLocalBookmark(item:GallerySummary,s:BookmarkStore=bookmarkStore()){return serialBookmark(async()=>{const items=await loadLocalBookmarks(s),old=items.find(value=>value.gid===item.gid&&value.token===item.token),next=makeBookmark(item,old);await saveLocalBookmarks([next,...items.filter(value=>value.gid!==next.gid||value.token!==next.token)],s);return next})}
export async function removeLocalBookmark(gid:string,token:string,s:BookmarkStore=bookmarkStore()){if(!/^\d+$/.test(gid)||!/^[a-f0-9]+$/i.test(token))throw new Error("书签身份无效。");return serialBookmark(async()=>{const items=await loadLocalBookmarks(s);await saveLocalBookmarks(items.filter(value=>value.gid!==gid||value.token!==token),s)})}
export async function clearLocalBookmarks(s:BookmarkStore=bookmarkStore()){return serialBookmark(async()=>saveLocalBookmarks([],s))}
export function localBookmarkSummary(value:LocalBookmarkV1):GallerySummary{const base=getBaseUrl(value.site);return{id:`${value.gid}:${value.token}`,gid:value.gid,token:value.token,title:value.title,category:value.category||"",thumb:value.thumb||"",posted:"",uploader:value.uploader||"",pages:value.pages||0,url:new URL(`g/${value.gid}/${value.token}/`,base).toString()}}

export type DownloadStatus="queued"|"paused"|"downloading"|"completed"|"failed"|"cancelled"
export type OfflineDownload={id:string;title:string;summary:GallerySummary;pages:Array<{index:number;pageUrl:string}>;done:number[];failed:number[];status:DownloadStatus;updatedAt:number}
type DownloadDb={schemaVersion:1;items:OfflineDownload[]}
type DownloadStore=PreferenceStore
const DOWNLOAD_ID=/^g-\d+-[a-f0-9]{8}$/i,MAX_DOWNLOADS=30
let downloadQueue:Promise<void>=Promise.resolve()
type ActiveDownload={controller:AbortController;finished:Promise<OfflineDownload|undefined>}
const activeDownloads=new Map<string,ActiveDownload>()
function downloadStore():DownloadStore{return fileStore("offline-downloads-v1.json","离线下载")}
function safeDownloadId(item:GallerySummary){const ref=parseGalleryRef(item.url);if(!ref)throw new Error("画廊身份无效。");return `g-${ref.gid}-${ref.token.slice(0,8)}`}
function offlineRoot(){return `${String(fm?.documentsDirectory||"")}/ehentai-library/offline`}
function validIndex(value:any){return Number.isInteger(value)&&value>=0}
function validDownload(value:any):value is OfflineDownload{if(!value||!DOWNLOAD_ID.test(String(value.id||""))||typeof value.title!=="string"||!value.summary||!Array.isArray(value.pages)||!Array.isArray(value.done)||!Array.isArray(value.failed)||!["queued","paused","downloading","completed","failed","cancelled"].includes(value.status)||!Number.isFinite(value.updatedAt))return false;const indexes=value.pages.map((page:any)=>page?.index);if(indexes.length!==new Set(indexes).size||!indexes.every(validIndex)||!value.pages.every((page:any)=>typeof page?.pageUrl==="string"&&page.pageUrl.startsWith("https://")))return false;const known=new Set(indexes),done=new Set(value.done),failed=new Set(value.failed);return [...done,...failed].every(index=>validIndex(index)&&known.has(index))&&![...done].some(index=>failed.has(index))}
export function parseDownloads(raw:string|null):OfflineDownload[]{if(!raw)return[];const x:DownloadDb=JSON.parse(raw);if(x?.schemaVersion!==1||!Array.isArray(x.items)||!x.items.every(validDownload))throw new Error("离线下载数据无法读取；原文件未被覆盖。");return x.items.map(item=>({...item,status:item.status==="downloading"?"paused":item.status,pages:item.pages.map(page=>({...page})),done:[...new Set(item.done)].sort((a,b)=>a-b),failed:[...new Set(item.failed)].sort((a,b)=>a-b)}))}
export async function loadDownloads(s:DownloadStore=downloadStore()){try{return parseDownloads(await s.read()).sort((a,b)=>b.updatedAt-a.updatedAt)}catch{throw new Error("离线下载数据无法读取；原文件未被覆盖。")}}
export function assertDownloadCapacity(items:ReadonlyArray<OfflineDownload>){if(items.length>=MAX_DOWNLOADS)throw new Error(`离线下载最多保留 ${MAX_DOWNLOADS} 项，请删除一个任务后再试。`)}
async function saveDownloads(items:OfflineDownload[],s:DownloadStore=downloadStore()){await s.write(JSON.stringify({schemaVersion:1,items}))}
function serialDownload<T>(work:()=>Promise<T>):Promise<T>{const next=downloadQueue.then(work,work);downloadQueue=next.then(()=>undefined,()=>undefined);return next}
async function updateDownload(id:string,fn:(item:OfflineDownload)=>OfflineDownload|undefined,s:DownloadStore=downloadStore()){if(!DOWNLOAD_ID.test(id))throw new Error("下载任务无效。");return serialDownload(async()=>{const items=await loadDownloads(s);let changed:OfflineDownload|undefined;const next=items.flatMap(item=>{if(item.id!==id)return[item];changed=fn(item);return changed?[changed]:[]});await saveDownloads(next,s);return changed})}
export async function createDownload(item:GallerySummary,s:DownloadStore=downloadStore()){const id=safeDownloadId(item);const existing=(await loadDownloads(s)).find(x=>x.id===id);if(existing)return existing;const detail=await loadGalleryDetail(item.url);assertCompletePreviewInventory(detail);const record:OfflineDownload={id,title:detail.title||item.title,summary:{...item,pages:detail.pageLinks.length},pages:detail.pageLinks.map(page=>({index:page.index,pageUrl:page.pageUrl})),done:[],failed:[],status:"queued",updatedAt:Date.now()};return serialDownload(async()=>{const latest=(await loadDownloads(s)).find(x=>x.id===id);if(latest)return latest;const items=await loadDownloads(s);assertDownloadCapacity(items);await saveDownloads([record,...items],s);return record})}
export type OfflineFileOps={exists(path:string):Promise<boolean>;remove(path:string):Promise<void>;rename(from:string,to:string):Promise<void>;writeAsData(path:string,data:any):Promise<void>;createDirectory(path:string,recursive:boolean):Promise<void>}
export async function writeOfflinePageAtomically(ops:OfflineFileOps,directory:string,target:string,data:any){const temp=`${target}.tmp`;try{if(await ops.exists(temp))await ops.remove(temp)}catch{}await ops.createDirectory(directory,true);await ops.writeAsData(temp,data);await ops.rename(temp,target)}
export async function deleteOfflineDirectoryTransaction(ops:Pick<OfflineFileOps,"exists"|"remove"|"rename">,directory:string,trash:string,saveManifest:()=>Promise<void>){const hasDirectory=await ops.exists(directory),hasTrash=await ops.exists(trash);if(hasDirectory&&hasTrash)throw new Error("离线文件清理未完成，请稍后重试。");if(!hasDirectory&&hasTrash)await ops.rename(trash,directory);let moved=false;if(await ops.exists(directory)){await ops.rename(directory,trash);moved=true}try{await saveManifest()}catch(error){if(moved){try{await ops.rename(trash,directory)}catch{throw new Error("离线文件清理未完成；请稍后重试。")}}throw error}if(moved){try{await ops.remove(trash)}catch{}}}
function offlinePagePath(id:string,index:number){if(!DOWNLOAD_ID.test(id)||!validIndex(index))throw new Error("离线文件身份无效。");return `${offlineRoot()}/${id}/${String(index).padStart(4,"0")}.img`}
function offlinePageTempPath(id:string,index:number){return `${offlinePagePath(id,index)}.tmp`}
async function writeOfflinePage(id:string,index:number,data:any){await writeOfflinePageAtomically(fm,`${offlineRoot()}/${id}`,offlinePagePath(id,index),data)}
function isAbort(error:unknown){return (error as any)?.name==="AbortError"||/abort/i.test(String((error as any)?.message||""))}
export function isImagePayload(contentType:string,data:any){const bytes=data?.toUint8Array?.()||data?.getBytes?.()||(data instanceof Uint8Array?data:null);return Boolean(/^image\//i.test(contentType)&&bytes?.length&&((bytes[0]===255&&bytes[1]===216&&bytes[2]===255)||(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)||(bytes[0]===82&&bytes[1]===73&&bytes[2]===70&&bytes[3]===70&&bytes[8]===87&&bytes[9]===69&&bytes[10]===66&&bytes[11]===80)))}
async function applyDownloadPage(id:string,index:number,ok:boolean,s:DownloadStore){return updateDownload(id,item=>{if(item.status!=="downloading")return item;const done=new Set(item.done),failed=new Set(item.failed);if(ok){done.add(index);failed.delete(index)}else if(!done.has(index))failed.add(index);return{...item,done:[...done].sort((a,b)=>a-b),failed:[...failed].sort((a,b)=>a-b),updatedAt:Date.now()}},s)}
export function markDownloadRunning(item:OfflineDownload):OfflineDownload{return{...item,status:"downloading",updatedAt:Date.now()}}
async function runDownloadWork(id:string,controller:AbortController,concurrency:number,s:DownloadStore,onUpdate?:(item:OfflineDownload)=>void){let current=await updateDownload(id,item=>markDownloadRunning(item),s);if(!current)throw new Error("下载任务不存在。");onUpdate?.(current);const existing=await offlinePagePaths(current);const recovered=current.pages.filter((page,index)=>Boolean(existing[index])).map(page=>page.index);if(recovered.length){current=await updateDownload(id,item=>{const done=new Set([...item.done,...recovered]),failed=item.failed.filter(index=>!done.has(index));return{...item,done:[...done].sort((a,b)=>a-b),failed,updatedAt:Date.now()}},s)||current}const pending=current.pages.filter(page=>!current!.done.includes(page.index));const worker=async()=>{while(!controller.signal.aborted){const page=pending.shift();if(!page)return;const requestController=new AbortController(),abortRequest=()=>requestController.abort(),timeout=setTimeout(abortRequest,20_000);controller.signal.addEventListener?.("abort",abortRequest,{once:true});try{const resolved=await resolveImagePage(page.pageUrl),cookie=getCookieHeader(resolved.imageUrl);const response:any=await fetch(resolved.imageUrl,{headers:{Referer:resolved.pageUrl,...(cookie?{Cookie:cookie}:{})},signal:requestController.signal});if(!response.ok)throw new Error("download failed");const data=await response.data();if(!isImagePayload(String(response.headers?.get?.("content-type")||""),data))throw new Error("下载内容不是有效图片。");if(controller.signal.aborted)return;const active=(await loadDownloads(s)).find(item=>item.id===id);if(!active||active.status!=="downloading")return;await writeOfflinePage(id,page.index,data);if(controller.signal.aborted)return;const changed=await applyDownloadPage(id,page.index,true,s);if(changed)onUpdate?.(changed)}catch(error){if(controller.signal.aborted)return;const changed=await applyDownloadPage(id,page.index,false,s);if(changed)onUpdate?.(changed)}finally{clearTimeout(timeout);controller.signal.removeEventListener?.("abort",abortRequest)}}};await Promise.all(Array.from({length:Math.min(3,Math.max(1,concurrency),pending.length)},worker));current=await updateDownload(id,item=>item.status!=="downloading"?item:{...item,status:item.done.length===item.pages.length?"completed":item.failed.length?"failed":"paused",updatedAt:Date.now()},s)||current;onUpdate?.(current);return current}
export async function runDownload(id:string,concurrency=2,s:DownloadStore=downloadStore(),onUpdate?:(item:OfflineDownload)=>void){if(activeDownloads.has(id))return (await loadDownloads(s)).find(item=>item.id===id);const controller=new AbortController(),finished=runDownloadWork(id,controller,concurrency,s,onUpdate);activeDownloads.set(id,{controller,finished});try{return await finished}finally{if(activeDownloads.get(id)?.finished===finished)activeDownloads.delete(id)}}
async function stopDownload(id:string,status:"paused"|"cancelled",s:DownloadStore){activeDownloads.get(id)?.controller.abort();return updateDownload(id,item=>({...item,status,updatedAt:Date.now()}),s)}
export async function pauseDownload(id:string,s:DownloadStore=downloadStore()){return stopDownload(id,"paused",s)}
export async function cancelDownload(id:string,s:DownloadStore=downloadStore()){return stopDownload(id,"cancelled",s)}
export async function deleteDownload(id:string,s:DownloadStore=downloadStore()){if(!DOWNLOAD_ID.test(id))throw new Error("下载任务无效。");const active=activeDownloads.get(id);if(active){active.controller.abort();await active.finished.catch(()=>{})}return serialDownload(async()=>{const items=await loadDownloads(s),item=items.find(x=>x.id===id);if(!item)return;const dir=`${offlineRoot()}/${id}`,trash=`${offlineRoot()}/.${id}.deleting`;await deleteOfflineDirectoryTransaction(fm,dir,trash,()=>saveDownloads(items.filter(x=>x.id!==id),s))})}
export function reconcileOfflineDownloadState(item:OfflineDownload,presentIndexes:ReadonlySet<number>):OfflineDownload{const done=item.done.filter(index=>presentIndexes.has(index)),missing=item.done.filter(index=>!presentIndexes.has(index)),failed=[...new Set([...item.failed,...missing])].filter(index=>!done.includes(index)).sort((a,b)=>a-b);return{...item,done,failed,status:done.length===item.pages.length?"completed":failed.length?"failed":"paused",updatedAt:Date.now()}}
export async function reconcileOfflineDownload(id:string,s:DownloadStore=downloadStore()){const item=(await loadDownloads(s)).find(value=>value.id===id);if(!item)throw new Error("下载任务不存在。");const files=await offlinePagePaths(item),present=new Set(item.pages.filter((_,index)=>Boolean(files[index])).map(page=>page.index));return updateDownload(id,current=>reconcileOfflineDownloadState(current,present),s)}
export async function offlinePagePaths(item:OfflineDownload){return Promise.all(item.pages.map(async page=>{const file=offlinePagePath(item.id,page.index);return await fm.isFile(file)?file:""}))}
export async function clearImageCache(){const dir=`${Script.directory}/.image-cache`;if(!(await fm.exists(dir))){(globalThis as any).__ehentaiClearImageMemoryCache?.();return 0}const files=await fm.readDirectory(dir,true);await fm.remove(dir);(globalThis as any).__ehentaiClearImageMemoryCache?.();return files.length}

