import type { GallerySummary } from "./extractors"
import { parseGalleryRef } from "./pure"
import { getBaseUrl } from "./account"
export type HistoryRecordV1={gid:string;token:string;site:"e"|"ex";title:string;thumb?:string;category?:string;uploader?:string;pages?:number;lastPageIndex?:number;viewedAt:number;updatedAt:number}
type Db={schemaVersion:1;history:HistoryRecordV1[]};export type HistoryStore={read():Promise<string|null>;write(value:string):Promise<void>}
export type ReaderPreferences={version:1;layout:"single"|"continuous";preload:number;preferOriginal:boolean}
export type SavedSearch={id:string;title:string;query:string;createdAt:number}
export type PreferenceStore={read():Promise<string|null>;write(value:string):Promise<void>}
const fm:any=(globalThis as any).FileManager,MAX=200,DEFAULT_PREFERENCES:ReaderPreferences={version:1,layout:"single",preload:2,preferOriginal:false};let historyQueue:Promise<void>=Promise.resolve()
function path(name:string){return `${String(fm?.documentsDirectory||"")}/ehentai-library/${name}`}
async function replaceFile(target:string,value:string){const temp=`${target}.tmp`,backup=`${target}.bak`;await fm.createDirectory(target.split("/").slice(0,-1).join("/"),true);await fm.writeAsString(temp,value);const hadOld=await fm.exists(target);try{if(hadOld){try{if(await fm.exists(backup))await fm.remove(backup)}catch{}await fm.rename(target,backup)}await fm.rename(temp,target);if(hadOld){try{await fm.remove(backup)}catch{}}}catch(error){try{if(!(await fm.exists(target))&&await fm.exists(backup))await fm.rename(backup,target)}catch{};throw error}}
function fileStore(name:string,label:string):HistoryStore{const p=path(name);return{async read(){try{const backup=`${p}.bak`;if(!(await fm.exists(p))&&await fm.exists(backup))await fm.rename(backup,p);return await fm.exists(p)?await fm.readAsString(p):null}catch{throw new Error(`${label}读取失败；原文件未被覆盖。`)}},async write(value){await replaceFile(p,value)}}}
function store():HistoryStore{return fileStore("history-v1.json","本地历史数据")}
function parseHistory(raw:string|null):Db{if(!raw)return{schemaVersion:1,history:[]};const x=JSON.parse(raw);if(x?.schemaVersion!==1||!Array.isArray(x.history))throw new Error("本地历史数据无法读取；原文件未被覆盖。");return{schemaVersion:1,history:x.history.filter((r:any)=>r&&/^\d+$/.test(r.gid)&&/^[a-f0-9]+$/i.test(r.token)).map((r:any)=>({...r,site:r.site==="ex"?"ex":"e"}))}}
export async function loadHistory(s:HistoryStore=store()){return (await parseHistory(await s.read())).history.sort((a,b)=>b.updatedAt-a.updatedAt)}
async function saveHistory(history:HistoryRecordV1[],s:HistoryStore){await s.write(JSON.stringify({schemaVersion:1,history:history.slice(0,MAX)}))}
function serial<T>(work:()=>Promise<T>):Promise<T>{const next=historyQueue.then(work,work);historyQueue=next.then(()=>undefined,()=>undefined);return next}
function makeRecord(item:GallerySummary,old:HistoryRecordV1|undefined):HistoryRecordV1|null{const ref=parseGalleryRef(item.url);if(!ref)return null;const now=Date.now(),site=new URL(item.url).hostname==="exhentai.org"?"ex":"e" as const;return{gid:ref.gid,token:ref.token,site,title:item.title,thumb:item.thumb,category:item.category,uploader:item.uploader,pages:item.pages,lastPageIndex:old?.lastPageIndex,viewedAt:old?.viewedAt||now,updatedAt:now}}
export async function recordHistory(item:GallerySummary,s:HistoryStore=store()){return serial(async()=>{const h=await loadHistory(s),old=h.find(x=>x.gid===item.gid&&x.token===item.token),record=makeRecord(item,old);if(!record)return;await saveHistory([record,...h.filter(x=>x.gid!==record.gid||x.token!==record.token)],s)})}
export async function updateReadingProgress(item:GallerySummary,index:number,s:HistoryStore=store()){if(!Number.isInteger(index)||index<0)return;return serial(async()=>{const h=await loadHistory(s),old=h.find(x=>x.gid===item.gid&&x.token===item.token),record=makeRecord(item,old);if(!record)return;record.lastPageIndex=record.pages&&index>=record.pages?record.pages-1:index;await saveHistory([record,...h.filter(x=>x.gid!==record.gid||x.token!==record.token)],s)})}
export function resumeIndex(r:Pick<HistoryRecordV1,"lastPageIndex"|"pages">,count:number){const x=Number(r.lastPageIndex);return Number.isInteger(x)&&x>=0&&x<count&&(!r.pages||x<r.pages)?x:null}
export function historySummary(r:HistoryRecordV1):GallerySummary{const base=getBaseUrl(r.site);return{id:`${r.gid}:${r.token}`,gid:r.gid,token:r.token,title:r.title,category:r.category||"",thumb:r.thumb||"",posted:"",uploader:r.uploader||"",pages:r.pages||0,url:new URL(`g/${r.gid}/${r.token}/`,base).toString()}}
export async function resetReadingProgress(gid:string,token:string,s:HistoryStore=store()){return serial(async()=>{const h=await loadHistory(s),r=h.find(x=>x.gid===gid&&x.token===token);if(!r)return;r.lastPageIndex=undefined;r.updatedAt=Date.now();await saveHistory(h,s)})}
export async function deleteHistory(gid:string,token:string,s:HistoryStore=store()){return serial(async()=>saveHistory((await loadHistory(s)).filter(x=>x.gid!==gid||x.token!==token),s))}
export async function clearHistory(s:HistoryStore=store()){return serial(async()=>saveHistory([],s))}
function normalizePreferences(raw:any):ReaderPreferences{return{version:1,layout:raw?.layout==="continuous"?"continuous":"single",preload:Math.max(0,Math.min(4,Number.isInteger(raw?.preload)?raw.preload:DEFAULT_PREFERENCES.preload)),preferOriginal:Boolean(raw?.preferOriginal)}}
function preferenceStore():PreferenceStore{return fileStore("preferences-v1.json","设置")}
export async function loadPreferences(s:PreferenceStore=preferenceStore()):Promise<ReaderPreferences>{const raw=await s.read();if(!raw)return{...DEFAULT_PREFERENCES};try{return normalizePreferences(JSON.parse(raw))}catch{throw new Error("设置数据无法读取；原文件未被覆盖。")} }
export async function savePreferences(update:Partial<ReaderPreferences>,s:PreferenceStore=preferenceStore()){const next=normalizePreferences({...await loadPreferences(s),...update});await s.write(JSON.stringify(next));return next}
type SearchDb={schemaVersion:1;items:SavedSearch[]}
function searchStore():PreferenceStore{return fileStore("quick-search-v1.json","快速搜索")}
export async function loadSavedSearches(s:PreferenceStore=searchStore()):Promise<SavedSearch[]>{const raw=await s.read();if(!raw)return[];try{const x:SearchDb=JSON.parse(raw);if(x?.schemaVersion!==1||!Array.isArray(x.items))throw new Error();return x.items.filter(i=>i&&typeof i.id==="string"&&typeof i.query==="string").sort((a,b)=>b.createdAt-a.createdAt).slice(0,30)}catch{throw new Error("快速搜索数据无法读取；原文件未被覆盖。")}}
export async function saveSearch(query:string,title=query,s:PreferenceStore=searchStore()){const value=String(query||"").trim();if(!value)throw new Error("搜索词不能为空。");const items=await loadSavedSearches(s),entry:SavedSearch={id:`saved_${Date.now().toString(36)}`,title:String(title||value).trim().slice(0,80)||value,query:value.slice(0,200),createdAt:Date.now()};await s.write(JSON.stringify({schemaVersion:1,items:[entry,...items.filter(i=>i.query!==entry.query)].slice(0,30)}));return entry}
export async function deleteSavedSearch(id:string,s:PreferenceStore=searchStore()){const items=await loadSavedSearches(s);await s.write(JSON.stringify({schemaVersion:1,items:items.filter(i=>i.id!==id)}))}
