import type { GallerySummary } from "./extractors"
import { parseGalleryRef } from "./pure"
import { getBaseUrl } from "./account"
export type HistoryRecordV1 = { gid:string; token:string; site:"e"|"ex"; title:string; thumb?:string; category?:string; uploader?:string; pages?:number; lastPageIndex?:number; viewedAt:number; updatedAt:number }
type Db={schemaVersion:1;history:HistoryRecordV1[]}; export type HistoryStore={read():Promise<string|null>;write(value:string):Promise<void>}
const fm:any=(globalThis as any).FileManager, MAX=200
function store():HistoryStore{const p=`${String(fm?.documentsDirectory||"")}/ehentai-library/history-v1.json`;return{async read(){try{if(!(await fm.exists(p)))return null;return await fm.readAsString(p)}catch(e){throw new Error("本地历史数据读取失败；原文件未被覆盖。")}},async write(v){const t=`${p}.tmp`;await fm.createDirectory(p.split("/").slice(0,-1).join("/"),true);await fm.writeAsString(t,v);await fm.move(t,p)}}}
function parse(raw:string|null):Db{if(!raw)return{schemaVersion:1,history:[]};const x=JSON.parse(raw);if(x?.schemaVersion!==1||!Array.isArray(x.history))throw new Error("本地历史数据无法读取；原文件未被覆盖。");return{schemaVersion:1,history:x.history.filter((r:any)=>r&&/^\d+$/.test(r.gid)&&/^[a-f0-9]+$/i.test(r.token)).map((r:any)=>({...r,site:r.site==="ex"?"ex":"e"}))}}
export async function loadHistory(s:HistoryStore=store()){return (await parse(await s.read())).history.sort((a,b)=>b.updatedAt-a.updatedAt)} async function save(h:HistoryRecordV1[],s:HistoryStore){await s.write(JSON.stringify({schemaVersion:1,history:h.slice(0,MAX)}))}
export async function recordHistory(item:GallerySummary,s:HistoryStore=store()){const ref=parseGalleryRef(item.url);if(!ref)return;const h=await loadHistory(s), old=h.find(x=>x.gid===ref.gid&&x.token===ref.token),now=Date.now(),site=new URL(item.url).hostname==="exhentai.org"?"ex":"e" as const;const r:HistoryRecordV1={gid:ref.gid,token:ref.token,site,title:item.title,thumb:item.thumb,category:item.category,uploader:item.uploader,pages:item.pages,lastPageIndex:old?.lastPageIndex,viewedAt:old?.viewedAt||now,updatedAt:now};await save([r,...h.filter(x=>x.gid!==ref.gid||x.token!==ref.token)],s)}
export async function updateReadingProgress(item:GallerySummary,index:number,s:HistoryStore=store()){if(!Number.isInteger(index)||index<0)return;await recordHistory(item,s);const h=await loadHistory(s),ref=parseGalleryRef(item.url),r=ref&&h.find(x=>x.gid===ref.gid&&x.token===ref.token);if(!r)return;r.lastPageIndex=r.pages&&index>=r.pages?r.pages-1:index;r.updatedAt=Date.now();await save(h,s)}
export function resumeIndex(r:Pick<HistoryRecordV1,"lastPageIndex"|"pages">,count:number){const x=Number(r.lastPageIndex);return Number.isInteger(x)&&x>=0&&x<count&&(!r.pages||x<r.pages)?x:null}
export function historySummary(r:HistoryRecordV1):GallerySummary{const base=getBaseUrl(r.site);return{id:`${r.gid}:${r.token}`,gid:r.gid,token:r.token,title:r.title,category:r.category||"",thumb:r.thumb||"",posted:"",uploader:r.uploader||"",pages:r.pages||0,url:new URL(`g/${r.gid}/${r.token}/`,base).toString()}}
export async function deleteHistory(gid:string,token:string,s:HistoryStore=store()){await save((await loadHistory(s)).filter(x=>x.gid!==gid||x.token!==token),s)} export async function clearHistory(s:HistoryStore=store()){await save([],s)}
