import { Button, HStack, List, NavigationLink, ProgressView, Section, Text, TextField, VStack, useEffect, useState } from "scripting"
import { loadFavorites, type FavoritesPage } from "./favorites"
import { clearHistory, deleteHistory, historySummary, loadHistory, type HistoryRecordV1 } from "./libraryStore"
import { EmptyState, ErrorText } from "./StateView"
import { GalleryDetailView } from "./GalleryFlow"

function GalleryLink({ item }: { item: any }) { return <NavigationLink destination={<GalleryDetailView summary={item} />}><VStack alignment="leading" spacing={4}><Text font="headline" lineLimit={2}>{item.title || "未命名画廊"}</Text><Text font="caption" foregroundStyle="secondaryLabel">{[item.category, item.uploader, item.pages ? `${item.pages} 页` : ""].filter(Boolean).join(" · ")}</Text></VStack></NavigationLink> }
export function FavoritesScene() { const [page, setPage] = useState<FavoritesPage | null>(null); const [category, setCategory] = useState<number | undefined>(); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = async (direct?: string) => { setLoading(true); setError(""); try { setPage(await loadFavorites(category, { query }, direct)) } catch (e) { setError(e instanceof Error ? e.message : "收藏读取失败") } finally { setLoading(false) } }; useEffect(() => { void load() }, [category]); return <List navigationTitle="收藏" overlay={loading && !page ? <ProgressView title="正在读取收藏…" progressViewStyle="circular" /> : undefined}><Section><TextField title="搜索收藏" value={query} onChanged={setQuery} prompt="名称、标签或备注" submitLabel="search" /><Button title="搜索收藏" disabled={loading} action={() => void load()} /><ErrorText message={error} /></Section>{page ? <Section header={<Text textCase={null}>分类</Text>}><VStack alignment="leading" spacing={8}>{page.categories.map(item => <Button key={String(item.index)} title={`${category === item.index ? "✓ " : ""}${item.name} · ${item.count}`} buttonStyle={category === item.index ? "borderedProminent" : "bordered"} action={() => setCategory(item.index)} />)}</VStack></Section> : null}<Section header={<Text textCase={null}>收藏列表</Text>}>{page?.items.map(item => <GalleryLink key={item.id} item={item} />)}{page && !page.items.length ? <EmptyState message="该收藏分类暂无画廊。" /> : null}{page?.nextHref ? <Button title="下一页" disabled={loading} action={() => void load(page.nextHref)} /> : null}{page?.prevHref ? <Button title="上一页" disabled={loading} action={() => void load(page.prevHref)} /> : null}</Section></List> }
export function HistoryScene() { const [records, setRecords] = useState<HistoryRecordV1[]>([]); const [error, setError] = useState(""); const load = async () => { try { setRecords(await loadHistory()); setError("") } catch (e) { setError(e instanceof Error ? e.message : "历史记录读取失败") } }; useEffect(() => { void load() }, []); return <List navigationTitle="历史"><Section><ErrorText message={error} />{records.map(record => <HStack key={`${record.gid}:${record.token}`}><VStack alignment="leading" frame={{maxWidth:"infinity"}}><GalleryLink item={historySummary(record)} />{record.lastPageIndex != null ? <Text font="caption" foregroundStyle="secondaryLabel">进度：第 {record.lastPageIndex + 1} 页</Text> : null}</VStack><Button title="删除" buttonStyle="bordered" action={() => { void deleteHistory(record.gid, record.token).then(load) }} /></HStack>)}{!error && !records.length ? <EmptyState message="尚无阅读历史。打开画廊详情后会自动记录。" /> : null}</Section>{records.length ? <Section><Button title="清空历史" role="destructive" action={() => { void prompt({ title: "清空全部历史？", message: "此操作会删除本机全部阅读历史和进度，无法撤销。", confirmLabel: "清空" }).then(confirmed => { if (confirmed) return clearHistory().then(load); }) }} /></Section> : null}</List> }
export function LibraryScene() { return <List navigationTitle="书库"><Section><NavigationLink destination={<FavoritesScene />}><Text>收藏</Text></NavigationLink><NavigationLink destination={<HistoryScene />}><Text>历史 / 继续阅读</Text></NavigationLink></Section></List> }
