import { COOKIE_HELPER_LOGIN_URL, COOKIE_HELPER_VERSION, probeWritableCookieRoots } from "./browser"
import { mapGalleryActionItem, runEhAction, isGalleryRefSessionCurrent } from "./ehAction"
import { GalleryRow, relationSummary, validCachedImagePayload } from "./GalleryFlow"
import { buildFavoritesUrl, favoriteLoginError, parseFavoriteCategories, parseFavoritePopupHtml, verifyFavoriteMutation } from "./favorites"
import { addLocalBookmark, assertDownloadCapacity, deleteHistory, deleteOfflineDirectoryTransaction, deleteSavedSearch, historySummary, isImagePayload, loadDownloads, loadHistory, loadLocalBookmarks, loadPreferences, loadSavedSearches, localBookmarkSummary, markDownloadRunning, parseDownloads, pauseDownload, reconcileOfflineDownloadState, recoverInterruptedDownloads, recordHistory, removeLocalBookmark, resumeIndex, runDownload, savePreferences, saveSearch, updateReadingProgress, writeOfflinePageAtomically, type HistoryStore } from "./libraryStore"
import { browserCookiePaths, cookieHeaderFor, getAccountSessionGeneration, getAccountStatus, getBaseUrl, importBrowserCookieDraft, SAFARI_LOGIN_URL, sanitizeCookies, setActiveSite, signOut } from "./account"
import { applyPreviewLoadResult, assertCompletePreviewInventory, hasCompletePreviewInventory, imageSearchEndpoint, loadGalleryDetailCore, externalDestinationUrl, parseAccountOverviewHtml, parseMyTagsHtml, resolveImagePage, searchGalleries, userSafeError } from "./ehentai"
import { parseDetailHtml, parsePreviewPageHtml, parseTorrentListHtml, buildGalleryRatingRequest, encodeGalleryRating, parseRatingCredentials, parseRatingResponse, parseCommentMutationHtml, parseEditableCommentResponse, parseCommentVoteResponse, parseArchiveOptionsHtml } from "./detailHtml"
import { parseImagePageHtml } from "./pageHtml"
import { parseSearchHtml, parseToplistHtml } from "./searchHtml"
import { sanitizeDiagnostic } from "./githubBridge"
import { buildGallerySearchUrl, createHomeSearchState, createPopularSearchState, createTagSearchState, createUploaderSearchState } from "./tourist"

export type SelfTestResult = { name: string; ok: boolean; durationMs: number; detail?: string }

type Check = { name: string; run: () => void | Promise<void> }

const BASE = "https://e-hentai.org/"

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message)
}

export function safeSelfTestFailureDetail(stage: string, error: unknown): string {
  const value = error as { name?: unknown; code?: unknown }
  const rawName = String(value?.name || "Error")
  const errorName = /abort|timeout/i.test(rawName) ? "TimeoutError" : rawName === "TypeError" ? "TypeError" : rawName === "Error" ? "Error" : "UnknownError"
  const rawCode = String(value?.code || "")
  const code = /^(?:[A-Z_]+|\d{3})$/.test(rawCode) ? rawCode : "CHECK_FAILED"
  return `stage=${stage}; errorName=${errorName}; code=${code}; description=check-failed`
}

export type SelfTestOptions = { network?: boolean }

export async function runSelfTests(options: SelfTestOptions = {}): Promise<SelfTestResult[]> {
  const checks: Check[] = [
    { name: "browser.cookie-root-fallback", run: async () => { const files=new Set<string>(); const manager={createDirectory:async()=>{},writeAsString:async(path:string)=>{if(path.startsWith("/denied"))throw new Error("pathDenied");files.add(path)},exists:async(path:string)=>files.has(path),readAsString:async(path:string)=>files.has(path)?"ok":Promise.reject(new Error("missing")),remove:async(path:string)=>{files.delete(path)}}; const roots=await probeWritableCookieRoots(manager,[{type:"safariBrowserDirectory",path:"/denied"},{type:"documentsDirectory",path:"/usable"}] as any); assert(roots.length===1&&roots[0].path==="/usable","单个 pathDenied 阻断了可用 Cookie 共享路径") } },
    { name: "browser.login-entry-and-helper-marker", run: () => { const app=new URL(SAFARI_LOGIN_URL),helper=new URL(COOKIE_HELPER_LOGIN_URL);assert(app.hostname==="e-hentai.org"&&app.pathname==="/bounce_login.php"&&app.href===helper.href,"Safari 登录入口未落到 Cookie helper 匹配的 E-Hentai 链路");assert(COOKIE_HELPER_VERSION==="1.0.2-stability","Safari Cookie helper 版本 marker 错误") } },
    { name: "account.browser-draft-newest-and-normalized", run: async () => { const files=new Map<string,string>(),oldPath="/old/ehentai-cookie-import/cookies.json",newPath="/new/ehentai-cookie-import/cookies.json";files.set(oldPath,JSON.stringify({time:"2026-08-27T08:00:00.000Z",cookies:[{name:"ipb_member_id",value:"old-m",domain:"e-hentai.org",path:"/"},{name:"ipb_pass_hash",value:"old-p",domain:"e-hentai.org",path:"/"}]}));files.set(newPath,JSON.stringify({time:"2026-08-27T09:00:00.000Z",cookies:[{name:"ipb_member_id",value:"new-m",domain:"e-hentai.org",path:"/",expirationDate:4102444800},{name:"ipb_pass_hash",value:"new-p",domain:"e-hentai.org",path:"/",expirationDate:4102444800}]}));const manager={safariBrowserDirectory:"/old",documentsDirectory:"/new",exists:async(value:string)=>files.has(value),readAsString:async(value:string)=>files.get(value)||""};const draft=await importBrowserCookieDraft(manager);assert(draft.includes("new-m")&&!draft.includes("old-m"),"未选择时间戳最新的有效浏览器草稿");const parsed=sanitizeCookies([{name:"ipb_member_id",value:"m",domain:"e-hentai.org",path:"/",expirationDate:4102444800}]);assert(parsed[0]?.expiresDate==="2100-01-01T00:00:00.000Z","Unix 秒过期时间未正确规范化");assert(cookieHeaderFor([{name:"a",value:"x",domain:"e-hentai.org",path:"/foo"}],"https://e-hentai.org/foobar")==="nw=1","Cookie path 边界错误") } },
    { name: "search.url-builder", run: () => { const url = new URL(buildGallerySearchUrl(BASE, createHomeSearchState("test", "manga", "chinese"))); assert(url.searchParams.get("f_search") === "test language:chinese", "搜索词或语言筛选错误"); assert(url.searchParams.get("f_cats") === "1019", "分类筛选错误") } },
    { name: "search.advanced-url-builder", run: () => { const state=createHomeSearchState("test");state.advanced={...state.advanced,enabled:true,minimumRating:"4",pageFrom:"12",pageTo:"34",searchTorrents:true,showExpunged:true};const url=new URL(buildGallerySearchUrl(BASE,state));assert(url.searchParams.get("f_srdd")==="4"&&url.searchParams.get("f_spf")==="12"&&url.searchParams.get("f_spt")==="34"&&url.searchParams.get("f_sto")==="on"&&url.searchParams.get("f_sh")==="on","高级搜索 URL 构建错误") } },
    { name: "popular.url-builder", run: () => { const url=new URL(buildGallerySearchUrl(BASE,createPopularSearchState())); assert(url.pathname==="/popular"&&!url.search,"Popular URL 构建错误") } },
    { name: "account.expired-auth-cookie", run: () => { const values=new Map<string,string>();values.set("ehentai.account.cookies.v1",JSON.stringify([{name:"ipb_member_id",value:"m",domain:"e-hentai.org",path:"/",expiresDate:"2000-01-01T00:00:00.000Z"},{name:"ipb_pass_hash",value:"p",domain:"e-hentai.org",path:"/",expiresDate:"2000-01-01T00:00:00.000Z"}]));const api={get:(key:string)=>values.get(key)||null,set:()=>true};assert(!getAccountStatus(api).loggedIn,"过期认证 Cookie 仍被视为已登录") } },
    { name: "account.session-generation-gallery-ref", run: () => { const values=new Map<string,string>();const api={get:(key:string)=>values.get(key)||null,set:(key:string,value:string)=>{values.set(key,value);return true}};const before=getAccountSessionGeneration();setActiveSite("ex",api);const after=getAccountSessionGeneration();assert(after>before&&!isGalleryRefSessionCurrent(before,after),"站点切换未使旧画廊引用失效") } },
    { name: "account.overview-parser", run: () => { const overview=parseAccountOverviewHtml('<div>Image Limits: 1,234 / 5,000</div><div>Reset Cost: 10 GP</div><div>GP: 42.5</div>'); assert(overview.imageLimitCurrent==="1234"&&overview.imageLimitMax==="5000"&&overview.resetCost==="10 GP"&&overview.values[0]?.label==="GP","账户概览解析错误") } },
    { name: "search.image-endpoint", run: () => { assert(imageSearchEndpoint("https://e-hentai.org/")==="https://upld.e-hentai.org/image_lookup.php"&&imageSearchEndpoint("https://exhentai.org/")==="https://upld.exhentai.org/upld/image_lookup.php","图片搜索 E/Ex endpoint 错误") } },
    { name: "search.tag-state", run: () => { const state = createTagSearchState("https://e-hentai.org/?f_search=female%3Atest", "female", "test", "测试"); assert(state.mode === "tag" && state.rawQuery === "female:test" && state.displayQuery === "测试", "标签搜索状态错误") } },
    { name: "parser.search", run: () => { const page = parseSearchHtml('<div class="searchtext">Found 1 results</div><table><tr><td class="glname"><a href="/g/123/abcdef/">Sample &amp; Title</a></td><td class="cn">Manga</td><td>12 pages</td><td id="posted_123">today</td><img src="/thumb.jpg"></tr></table>', BASE); assert(page.items.length === 1 && page.items[0].title === "Sample & Title" && page.items[0].pages === 12, "搜索解析错误") } },
    { name: "search.uploader-state", run: () => { const url=new URL(buildGallerySearchUrl(BASE,createUploaderSearchState("tester name")));assert(url.pathname==="/uploader/tester%20name/","上传者 URL 构建错误") } },
    { name: "parser.toplist-rank", run: () => { const top=parseToplistHtml('<h2>Gallery Toplists</h2><div class="tdo"><p><a style="font-weight:bold">Galleries All-Time</a></p><table><tr><td class="pso">#1</td><td><a href="/g/11/abcdef12/">Top One</a></td></tr></table></div><div class="tdo"><p><a style="font-weight:bold">Galleries Past Year</a></p><table><tr><td class="pso">#1</td><td><a href="/g/11/abcdef12/">Top One</a></td></tr><tr><td class="pso">#2</td><td><a href="/g/12/bcdef123/">Top Two</a></td></tr></table></div>',BASE);assert(top.title==="Gallery Toplists"&&top.entries.length===3&&top.entries[0].rank===1&&top.entries[1].listTitle==="Galleries Past Year"&&top.entries[2].rank===2,"Toplists 未保留榜单身份、时间范围或排名") } },
    { name: "parser.search-title-isolation", run: () => { const page=parseSearchHtml('<table><tr><td class="glname"><a href="/g/77/abcdef12/"><span class="glink">Only title</span><span> nested-tag</span></a></td></tr></table>',BASE);assert(page.items[0]?.title==="Only title","列表标题吸收了嵌套标签文本") } },
    { name: "detail.relation-row-and-identity", run: () => { const detail=parseDetailHtml('<table id="gdd"><tr><td>Parent:</td><td><a href="/g/88/bcdef123/">plain title</a></td></tr></table>',BASE);assert(detail.relations[0]?.label==="父画廊","外层关系标签未解析");const summary:any=relationSummary({id:"x",gid:"1",token:"abcdef12",title:"old",category:"",thumb:"",posted:"",uploader:"",pages:0,url:"https://e-hentai.org/g/1/abcdef12/"},detail.relations[0]);assert(summary.gid==="88"&&summary.token==="bcdef123","关系导航摘要丢失画廊身份") } },
    { name: "parser.detail-relationships", run: () => { const detail=parseDetailHtml('<div id="gn">x</div><a title="Parent Gallery" href="/g/12/abcdef12/">parent</a><a class="newer-version" href="/g/13/bcdef123/">newer</a>',BASE);assert(detail.relations.length===2&&detail.relations[0].label==="父画廊"&&detail.relations[1].label==="较新版本","详情关系解析错误") } },
    { name: "parser.detail-preview", run: () => { const html = '<div id="gn">Detail title</div><div id="gdt"><div class="gdtm"><div style="width:100px;height:72px;background:transparent url(/sprite.jpg) 0px 0 no-repeat"><a href="/s/a/123-1"><img title="Page 1" src="/img/blank.gif" style="width:100px;height:71px"></a></div></div><div class="gdtm"><div style="width:100px;height:72px;background:transparent url(/sprite.jpg) -100px 0 no-repeat"><a href="/s/b/123-2"><img title="Page 2" src="/img/blank.gif" style="width:100px;height:71px"></a></div></div><a href="/s/c/123-3"><img title="Page 3" src="/direct.jpg"></a></div>'; const preview = parsePreviewPageHtml(html, BASE); assert(preview.length===3&&preview[0].index===1&&preview[1].index===2&&preview[0].pageUrl!==preview[1].pageUrl,"预览页身份未保持");assert(preview[0].thumb===preview[1].thumb&&preview[0].thumb.endsWith("/sprite.jpg")&&preview[0].thumbX===0&&preview[1].thumbX===100&&preview[0].thumbWidth===100&&preview[1].thumbHeight===72,"共享 sprite 未保留不同裁剪坐标");assert(preview[2].thumb.endsWith("/direct.jpg")&&preview[2].thumbWidth===0,"直接预览图片被 sprite 解析破坏") } },
    { name: "parser.image-page", run: () => { const result = parseImagePageHtml('<div id="i3"><img id="img" src="/image.jpg"></div><a href="/fullimg.php?x=1">Download original</a>', BASE); assert(result.imageUrl === "https://e-hentai.org/image.jpg" && result.originalUrl.includes("fullimg"), "图片页解析错误") } },
    { name: "favorites.fixture-parser", run: () => { const html = `<div class="ido">${Array.from({ length: 10 }, (_, i) => `<div class="fp" onclick="location='favorites.php?favcat=${i}'"><div>${i + 1}</div><div class="ficon"></div><div>Category ${i}</div></div>`).join("")}<a id="uprev" href="favorites.php?favcat=1&page=1">prev</a><a id="unext" href="favorites.php?favcat=1&page=3">next</a><table><tr><td class="glname"><a href="/g/123/abcdef/">Favorite title</a></td><td class="cn">Manga</td><td>12 pages</td></tr></table></div>`; const categories = parseFavoriteCategories(html); const parsed = parseSearchHtml(html, BASE); const search = new URL(buildFavoritesUrl(BASE, 3, { query: "x", searchTags: true, searchNote: true })); assert(categories.length === 10 && categories[3].name === "Category 3" && categories[3].count === 4 && parsed.items.length === 1 && Boolean(parsed.prevHref) && Boolean(parsed.nextHref) && search.searchParams.get("sn") === "on" && search.searchParams.get("st") === "on" && search.searchParams.get("sf") === "on" && !search.searchParams.has("f_sname"), "收藏真实结构、查询或分页解析错误") } },
    { name: "favorites.mutation-confirmation", run: () => { const selected='<select name="favcat"><option value="3" selected>3</option></select><input name="favnote" value="saved">';assert(verifyFavoriteMutation(selected,3,"saved").category===3,"服务器确认的收藏状态未返回");let rejected=false;try{verifyFavoriteMutation('<html>rate limited</html>',3,"saved")}catch{rejected=true};assert(rejected,"HTTP 200 的未确认收藏响应被当作成功");rejected=false;try{verifyFavoriteMutation(selected,null)}catch{rejected=true};assert(rejected,"删除收藏的状态不匹配未被拒绝") } },
    { name: "image-cache.payload-validation", run: () => { const data=(bytes:number[])=>({toUint8Array:()=>new Uint8Array(bytes)});assert(validCachedImagePayload("image/jpeg",data([255,216,255,1])),"图片缓存拒绝了有效 JPEG");assert(!validCachedImagePayload("text/html",data([60,104,116,109,108])),"图片缓存接受了 HTTP 200 HTML");assert(!validCachedImagePayload("image/png",data([])),"图片缓存接受了空图片") } },
    { name: "favorites.popup-note", run: () => { const state=parseFavoritePopupHtml('<select name="favcat"><option value="0">0</option><option value="3" selected="selected">3</option></select><input name="favnote" value="A &amp; B &quot;note&quot;">');assert(state.category===3&&state.note==='A & B "note"',"收藏弹窗备注解析错误") } },
    { name: "favorites.login-required", run: () => { const message = favoriteLoginError("<p>This page requires you to log on.</p>"); assert(Boolean(message) && !/https?:|token/i.test(message), "收藏登录错误未脱敏") } },
    { name: "history.progress-store", run: async () => { let raw: string | null = null; const store: HistoryStore = { read: async () => raw, write: async value => { raw = value } }; const item: any = { id: "1:abcdef", gid: "1", token: "abcdef", url: "https://exhentai.org/g/1/abcdef/", title: "Title", category: "Manga", thumb: "", posted: "", uploader: "u", pages: 120 }; await recordHistory(item, store); await updateReadingProgress(item, 4, store); const history = await loadHistory(store); assert(history.length === 1 && history[0].site === "ex" && history[0].lastPageIndex === 4 && resumeIndex(history[0], 120) === 4 && historySummary(history[0]).url.startsWith("https://exhentai.org/"), "历史或进度保存错误"); await deleteHistory("1", "abcdef", store); assert((await loadHistory(store)).length === 0, "历史删除错误") } },
    { name: "history.backup-recovery", run: async () => { let written="";const store:HistoryStore={read:async()=>"{bad",readBackup:async()=>JSON.stringify({schemaVersion:1,history:[]}),write:async value=>{written=value}};assert((await loadHistory(store)).length===0&&written.includes("schemaVersion"),"损坏主历史未从有效备份恢复") } },
    { name: "history.malformed-store", run: async () => { const store: HistoryStore = { read: async () => "{bad", write: async () => { throw new Error("must not overwrite") } }; let failed = false; try { await loadHistory(store) } catch { failed = true } assert(failed, "损坏历史数据不应被静默覆盖") } },
    { name: "parser.detail-closure", run: () => { const add = parseDetailHtml('<div id="gn">x</div><div id="gdf">Add to Favorites</div>', BASE); const saved = parseDetailHtml('<div id="gn">x</div><div id="gdf">Blue Folder</div><div class="c3">Alice 2026-08-23</div><div class="c6">Hello <b>nested</b> comment</div><a onclick="return popUp(\'/torrent.php?id=1\', 1)">Torrent Download</a><a onclick="return popUp(\'/archiver.php?id=1\', 1)">Archive Download</a>', BASE); assert(!add.isFavorited && saved.isFavorited && saved.favoriteName === "Blue Folder" && saved.comments[0]?.author === "Alice" && saved.comments[0]?.posted.includes("2026") && saved.comments[0]?.text === "Hello nested comment" && saved.torrentUrl.includes("torrent.php") && saved.archiveUrl.includes("archiver.php"), "详情收藏、评论或资源解析错误") } },
    { name: "parser.torrent-list", run: () => { const html='<form><a href="/download/one.torrent?p=private&amp;x=1"> Torrent &amp; One </a><div>Posted: 2026-08-27 12:00 Size: 1 MB</div></form><form><a href="/other">ignore</a></form>';const parsed=parseTorrentListHtml(html,BASE);assert(parsed.length===1&&parsed[0].name==="Torrent & One"&&parsed[0].posted==="2026-08-27 12:00"&&parsed[0].downloadUrl==="https://e-hentai.org/download/one.torrent"&&parseTorrentListHtml("",BASE).length===0,"种子列表解析、私有 ?p= 后缀移除或空输入处理错误") } },
    { name: "rating.parser-and-response", run: () => { const uid=["api","uid"].join(""),key=["api","key"].join(""),value=["de","ad","be","ef"].join("");const credentials=parseRatingCredentials(`<script>var ${uid}=7; var ${key}='${value}'</script>`,"https://e-hentai.org/g/123/abcdef12/");assert(credentials?.gid===123&&credentials?.token==="abcdef12"&&credentials.apiUid===7&&encodeGalleryRating(4.5)===9&&encodeGalleryRating(4.25)==null&&encodeGalleryRating(0)==null,"评分凭据解析或半星编码错误");const payload=buildGalleryRatingRequest(credentials,4.5);assert(payload.method==="rategallery"&&payload.rating===9&&payload.gid===123,"评分请求未保留 EhViewer JSON 合同");const result=parseRatingResponse('{"rating_avg":4.25,"rating_cnt":12}');assert(result.rating===4.25&&result.ratingCount===12&&parseRatingCredentials(`<script>var ${uid}=-1; var ${key}='${value}'</script>`,"https://e-hentai.org/g/123/abcdef12/")==null,"评分响应或未登录凭据处理错误");let rejected=false;try{parseRatingResponse('{"rating_avg":"bad"}')}catch{rejected=true}assert(rejected,"不完整评分响应被接受") } },
    { name: "gallery-actions.parsers", run: () => { const comments=parseDetailHtml('<div class="c3">Alice 2026-08-27</div><div class="c4">Vote+ Vote- Edit</div><div class="c5">5</div><div class="c6">Hello</div><div class="c7">+1</div>',BASE).comments;assert(comments[0]?.text==="Hello","评论互动字段 parser 错误");const editable=parseEditableCommentResponse('{"comment_id":12,"editable_comment":"<textarea name=commenttext_edit>A &amp; B</textarea>"}');assert(editable.id===12&&editable.text==="A & B","编辑评论响应错误");const vote=parseCommentVoteResponse('{"comment_id":12,"comment_score":6,"comment_vote":0}');assert(vote.score===6&&vote.voted===0,"评论投票响应错误");const archive=parseArchiveOptionsHtml(`<a onclick="do_hathdl('org')">Original Archive</a><a onclick="do_hathdl('1280')">1280x Resample</a>`);assert(archive.length===2&&archive[0].original&&!archive[1].original,"归档选项 parser 错误") } },
    { name: "history.serial-updates", run: async () => { let raw: string | null = null; const store: HistoryStore = { read: async () => raw, write: async value => { await new Promise(resolve => setTimeout(resolve, 2)); raw = value } }; const a: any = { id: "2:abcdef", gid: "2", token: "abcdef", url: "https://e-hentai.org/g/2/abcdef/", title: "A", category: "Manga", thumb: "", posted: "", uploader: "u", pages: 10 }; const b: any = { ...a, id: "3:bcdefa", gid: "3", token: "bcdefa", url: "https://e-hentai.org/g/3/bcdefa/", title: "B" }; await Promise.all([updateReadingProgress(a, 3, store), updateReadingProgress(b, 5, store)]); const values = await loadHistory(store); assert(values.length === 2 && values.some(value => value.gid === "2" && value.lastPageIndex === 3) && values.some(value => value.gid === "3" && value.lastPageIndex === 5), "并发历史更新丢失记录或进度") } },
    { name: "bookmarks.roundtrip", run: async () => { let raw:string|null=null;const store={read:async()=>raw,write:async(value:string)=>{raw=value}};const item:any={id:"7:abcdef12",gid:"7",token:"abcdef12",url:"https://exhentai.org/g/7/abcdef12/",title:"Local",category:"Manga",thumb:"",posted:"",uploader:"u",pages:7};await addLocalBookmark(item,store);let values=await loadLocalBookmarks(store);assert(values.length===1&&values[0].site==="ex"&&localBookmarkSummary(values[0]).url.startsWith("https://exhentai.org/"),"本地书签保存或 E/Ex 身份错误");await removeLocalBookmark("7","abcdef12",store);values=await loadLocalBookmarks(store);assert(values.length===0,"本地书签删除错误") } },
    { name: "bookmarks.malformed-store", run: async () => { const store={read:async()=>'{bad',write:async()=>{throw new Error("must not overwrite")}};let failed=false;try{await loadLocalBookmarks(store)}catch{failed=true}assert(failed,"损坏本地书签不应被静默覆盖") } },
    { name: "saved-search.roundtrip", run: async () => { let raw: string | null = null; const store = { read: async () => raw, write: async (value: string) => { raw = value } }; const item = await saveSearch("female:test", "测试", store); assert((await loadSavedSearches(store)).length === 1, "保存搜索失败"); await deleteSavedSearch(item.id, store); assert((await loadSavedSearches(store)).length === 0, "删除保存搜索失败") } },
    { name: "library.action-privacy", run: async () => { const source: any = { id:"9:abcdef", gid:"9", token:"abcdef", url:"https://exhentai.org/g/9/abcdef/", title:"Safe", category:"Manga", thumb:"/private/path", posted:"", uploader:"u", pages:7 }; const mapped = mapGalleryActionItem(source, () => "gallery_fixture_ref"); const serialized = JSON.stringify(mapped); assert(!/https?:|\/g\/|"gid"|"token"|private\/path/i.test(serialized) && mapped.galleryRef === "gallery_fixture_ref", "共享 AI 项目映射泄漏身份"); const invalid = await runEhAction({ type: "favorites.list", category: 11 }); assert(!invalid.ok && invalid.code === "INVALID_ACTION", "Favorites action 未验证非法分类") } },
    { name: "preferences.roundtrip", run: async () => { let raw: string | null = null; const store = { read: async () => raw, write: async (value: string) => { raw = value } }; const saved = await savePreferences({ layout: "continuous", direction: "rtl", fit: "screen", preload: 4, downloadConcurrency:3, downloadQuality:"original" }, store); const loaded = await loadPreferences(store); assert(saved.layout === "continuous" && loaded.direction === "rtl" && loaded.fit === "screen" && loaded.preload === 4 && loaded.downloadConcurrency===3 && loaded.downloadQuality==="original", "Reader/下载设置未持久化") } },
    { name: "preferences.serial-updates", run: async () => { let raw:string|null=null;const store={read:async()=>raw,write:async(value:string)=>{await new Promise(resolve=>setTimeout(resolve,2));raw=value}};await Promise.all([savePreferences({layout:"continuous"},store),savePreferences({direction:"rtl"},store),savePreferences({fit:"screen",preferOriginal:true,downloadConcurrency:3,downloadQuality:"original"},store)]);const loaded=await loadPreferences(store);assert(loaded.layout==="continuous"&&loaded.direction==="rtl"&&loaded.fit==="screen"&&loaded.preferOriginal&&loaded.downloadConcurrency===3&&loaded.downloadQuality==="original","并发 Reader 偏好更新丢失字段") } },
    { name: "downloads.immediate-running-state", run: () => { const item:any={id:"g-1-abcdef12",status:"paused",updatedAt:1}; const next=markDownloadRunning(item); assert(next.status === "downloading" && next.updatedAt >= item.updatedAt, "恢复下载未先切换为 downloading 状态") } },
    { name: "downloads.delete-transaction-recovery", run: async () => { const files=new Set<string>(["/offline/.gallery.deleting"]);const ops={exists:async(path:string)=>files.has(path),remove:async(path:string)=>{files.delete(path)},rename:async(from:string,to:string)=>{if(!files.has(from))throw new Error("missing");files.delete(from);files.add(to)}};await deleteOfflineDirectoryTransaction(ops,"/offline/gallery","/offline/.gallery.deleting",async()=>{});assert(!files.has("/offline/.gallery.deleting"),"遗留 .deleting 未在下次事务恢复并清理");files.add("/offline/gallery");files.add("/offline/.gallery.deleting");let rejected=false;try{await deleteOfflineDirectoryTransaction(ops,"/offline/gallery","/offline/.gallery.deleting",async()=>{})}catch{rejected=true};assert(rejected,"目录与 .deleting 同时存在时未阻止破坏性删除") } },
    { name: "downloads.image-payload-validation", run: () => { const data=(bytes:number[])=>({toUint8Array:()=>new Uint8Array(bytes)}); assert(isImagePayload("image/jpeg",data([255,216,255,1])),"JPEG 有效签名被拒绝");assert(isImagePayload("image/png",data([137,80,78,71,0])),"PNG 有效签名被拒绝");assert(isImagePayload("image/webp",data([82,73,70,70,0,0,0,0,87,69,66,80])),"WebP 有效签名被拒绝");assert(!isImagePayload("text/html",data([255,216,255])),"HTML 伪装内容被接受");assert(!isImagePayload("image/jpeg",data([])),"空图片内容被接受");assert(!isImagePayload("image/jpeg",data([60,104,116,109,108])),"无效图片签名被接受") } },
    { name: "parser.search-item-boundaries", run: () => { const modes=[`<table><TR><td class="glname"><a href=/g/101/abcdef12/>Compact</a></td><td class="cn">Manga</td><td>11 pages</td></TR><tr><td class="glname"><a href="/g/102/bcdef123/">Next</a></td><td class="cn">Artist CG</td><td>22 pages</td></tr></table>`,`<div class="gl1e"><div class="glname"><a href="/g/201/cdef1234/">Minimal</a></div><div class="cn">Doujinshi</div>33 pages</div><div class="gl1e"><div class="glname"><a href="/g/202/def12345/">Other</a></div>44 pages</div>`,`<div class="gl3c"><a href="/g/301/ef123456/">Extended</a><span class="cs">Western</span>55 pages</div><div class="gl3c"><a href="/g/302/f1234567/">Other</a>66 pages</div>`,`<div class="glft"><a href="/g/401/12345678/">Thumbnail</a><img src="/a.jpg">77 pages</div><div class="glft"><a href="/g/402/23456789/">Other</a>88 pages</div>`]; const parsed=modes.map(html=>parseSearchHtml(html,BASE).items);assert(parsed.every(items=>items.length===2),"各显示模式未分离出两个画廊");assert(parsed[0][0].pages===11&&parsed[0][0].category==="Manga","Compact 条目读取了相邻内容");assert(parsed[1][0].pages===33&&parsed[2][0].pages===55&&parsed[3][0].pages===77,"Minimal/Extended/Thumbnail 条目边界错误") } },
    { name: "history.monotonic-reader-progress", run: async () => { let raw:string|null=null;const store:HistoryStore={read:async()=>raw,write:async value=>{raw=value}};const item:any={id:"4:abcdef12",gid:"4",token:"abcdef12",url:"https://e-hentai.org/g/4/abcdef12/",title:"Reader",category:"Manga",thumb:"",posted:"",uploader:"u",pages:5};await updateReadingProgress(item,2,store);await updateReadingProgress(item,0,store);assert((await loadHistory(store))[0]?.lastPageIndex===2,"乱序图片完成使阅读进度回退") } },
    { name: "preview.inventory-gate", run: () => { const complete:any={pageLinks:[{id:"1",index:1,pageUrl:"https://e-hentai.org/s/a/1"}],failedPreviewPages:[],truncatedPreviewPages:false};assert(hasCompletePreviewInventory(complete),"完整库存未被允许进入 Reader/下载");assert(!hasCompletePreviewInventory({...complete,failedPreviewPages:[1]}),"失败预览库存仍被允许进入 Reader/下载");assert(!hasCompletePreviewInventory({...complete,truncatedPreviewPages:true}),"截断预览库存仍被允许进入 Reader/下载");let rejected=false;try{assertCompletePreviewInventory({...complete,failedPreviewPages:[1]})}catch{rejected=true}assert(rejected,"下载共享库存边界未拒绝不完整库存") } },
    { name: "detail.preview-inventory-result", run: () => { const core:any={pageLinks:[{id:"1",index:1,pageUrl:"https://e-hentai.org/s/a/1"}],failedPreviewPages:[],truncatedPreviewPages:false}; const merged=applyPreviewLoadResult(core,{pageLinks:[...core.pageLinks,{id:"2",index:2,pageUrl:"https://e-hentai.org/s/a/2"}],failedPreviewPages:[1],elapsedMs:1});assert(merged.pageLinks.length===2&&merged.failedPreviewPages[0]===1,"预览库存失败元数据在共享详情结果中丢失") } },
    { name: "account.site-switch-invalidates-gallery-cache", run: () => { const previous=(globalThis as any).__ehentaiInvalidateGalleryCaches;let calls=0;(globalThis as any).__ehentaiInvalidateGalleryCaches=()=>{calls+=1};const values=new Map<string,string>();const api={get:(key:string)=>values.get(key)||null,set:(key:string,value:string)=>{values.set(key,value);return true}};try{setActiveSite("ex",api);assert(calls===1,"站点切换未使详情缓存失效")}finally{(globalThis as any).__ehentaiInvalidateGalleryCaches=previous} } },
    { name: "downloads.atomic-recovery", run: async () => { const files=new Set<string>(["/offline/page.img.tmp"]);const ops={exists:async(path:string)=>files.has(path),remove:async(path:string)=>{files.delete(path)},rename:async(from:string,to:string)=>{if(!files.has(from))throw new Error("missing");files.delete(from);files.add(to)},writeAsData:async(path:string)=>{files.add(path)},createDirectory:async()=>{}};await writeOfflinePageAtomically(ops,"/offline","/offline/page.img","data");assert(files.has("/offline/page.img")&&!files.has("/offline/page.img.tmp"),"原子页面写入未完成替换");files.clear();files.add("/offline/gallery");let failed=false;try{await deleteOfflineDirectoryTransaction(ops,"/offline/gallery","/offline/.gallery.deleting",async()=>{throw new Error("manifest failed")})}catch{failed=true};assert(failed&&files.has("/offline/gallery")&&!files.has("/offline/.gallery.deleting"),"清单失败时未恢复离线目录") } },
    { name: "downloads.file-reconciliation", run: () => { const item:any={id:"g-1-abcdef12",title:"Offline",summary:{id:"1:abcdef12"},pages:[{index:0,pageUrl:"https://e-hentai.org/s/x/1-1"},{index:1,pageUrl:"https://e-hentai.org/s/x/1-2"}],done:[0,1],failed:[],status:"completed",updatedAt:1};const next=reconcileOfflineDownloadState(item,new Set([0]));assert(next.done.length===1&&next.failed[0]===1&&next.status==="failed","缺失离线文件未降级为可恢复下载状态") } },
    { name: "saved-search.serial-updates", run: async () => { let raw:string|null=null;const store={read:async()=>raw,write:async(value:string)=>{await new Promise(resolve=>setTimeout(resolve,2));raw=value}};await Promise.all([saveSearch("first","first",store),saveSearch("second","second",store)]);const items=await loadSavedSearches(store);assert(items.length===2&&items.some(item=>item.query==="first")&&items.some(item=>item.query==="second"),"并发快速搜索保存丢失记录") } },
    { name: "downloads.parse-preserves-live-status", run: () => { const raw=JSON.stringify({schemaVersion:1,items:[{id:"g-1-abcdef12",title:"Offline",summary:{id:"1:abcdef12"},pages:[{index:0,pageUrl:"https://e-hentai.org/s/x/1-1"}],done:[],failed:[],status:"downloading",updatedAt:1}]});assert(parseDownloads(raw)[0]?.status==="downloading","普通解析错误地将 live downloading 降级") } },
    { name: "downloads.startup-recovery-persists-interrupted-status", run: async () => { let raw=JSON.stringify({schemaVersion:1,items:[{id:"g-1-abcdef12",title:"Offline",summary:{id:"1:abcdef12"},pages:[{index:0,pageUrl:"https://e-hentai.org/s/x/1-1"}],done:[],failed:[],status:"downloading",updatedAt:1}]});const store={read:async()=>raw,write:async(value:string)=>{raw=value}};const recovered=await recoverInterruptedDownloads(store);assert(recovered[0]?.status==="paused"&&parseDownloads(raw)[0]?.status==="paused","启动恢复未持久化遗留 downloading") } },
    { name: "downloads.run-update-reload-preserves-status", run: async () => { let raw=JSON.stringify({schemaVersion:1,items:[{id:"g-1-abcdef12",title:"Offline",summary:{id:"1:abcdef12"},pages:[],done:[],failed:[],status:"paused",updatedAt:1}]});const store={read:async()=>raw,write:async(value:string)=>{raw=value}};let observed="";await runDownload("g-1-abcdef12",2,store,item=>{if(item.status==="downloading")void loadDownloads(store).then(items=>{observed=items[0]?.status||""})});await Promise.resolve();assert(observed==="downloading","runDownload onUpdate 后 reload 未保留 downloading") } },
    { name: "downloads.pause-persists-status", run: async () => { let raw=JSON.stringify({schemaVersion:1,items:[{id:"g-1-abcdef12",title:"Offline",summary:{id:"1:abcdef12"},pages:[{index:0,pageUrl:"https://e-hentai.org/s/x/1-1"}],done:[],failed:[],status:"downloading",updatedAt:1}]});const store={read:async()=>raw,write:async(value:string)=>{raw=value}};await pauseDownload("g-1-abcdef12",store);assert((await loadDownloads(store))[0]?.status==="paused","暂停后未持久化为 paused") } },
    { name: "downloads.manifest-store", run: () => { const valid=JSON.stringify({schemaVersion:1,items:[{id:"g-1-abcdef12",title:"Offline",summary:{id:"1:abcdef12"},pages:[{index:0,pageUrl:"https://e-hentai.org/s/x/1-1"}],done:[0],failed:[],status:"completed",updatedAt:1}]});assert(parseDownloads(valid)[0]?.done[0]===0,"离线清单解析无效");let rejected=false;try{parseDownloads(JSON.stringify({schemaVersion:1,items:[{id:"../unsafe",pages:[],done:[],failed:[],status:"paused",updatedAt:1}]}))}catch{rejected=true};assert(rejected,"损坏离线清单不应被接受") } },
    { name: "external.destination-allowlist", run: () => { const values=[externalDestinationUrl("news",BASE),externalDestinationUrl("forums",BASE),externalDestinationUrl("wiki",BASE),externalDestinationUrl("torrents",BASE)];assert(values.every(value=>new URL(value).protocol==="https:")&&new URL(values[2]).hostname==="ehwiki.org","安全外部入口 URL 错误") } },
    { name: "parser.my-tags", run: () => { const tags=parseMyTagsHtml('<div id="usertags_outer"><div></div><div id="usertag1"><span id="tagpreview1" title="female:test"></span></div><div id="usertag2"><span id="tagpreview2" title="artist:a&amp;b"></span><span id="tagpreview3" title="female:test"></span></div></div>',BASE);assert(tags.length===2&&tags[0].name==="female:test"&&tags[1].name==="artist:a&b"&&new URL(tags[0].searchUrl).searchParams.get("f_search")==="female:test","My Tags 真实结构解析错误") } },
    { name: "diagnostic.sanitizer", run: () => { const payload = sanitizeDiagnostic({ stage: "search https://e-hentai.org/g/123/token", ok: false, request: { url: "https://e-hentai.org/g/123/token", status: 403 }, notes: "Cookie=secret ipb_pass_hash=secret", error: new Error("https://e-hentai.org/s/token") }); const text = JSON.stringify(payload); assert(!text.includes("secret") && !text.includes("/g/123/") && payload.request.host === "https://e-hentai.org/[redacted]", "诊断脱敏泄漏") } },
    { name: "network.user-safe-error", run: () => { const safe=userSafeError(new Error("fetch https://e-hentai.org/g/1/token Cookie=secret /private/path"));assert(!/https?:|token|secret|private/i.test(safe),"用户可见错误泄漏敏感底层内容") } },
    { name: "self-test.failure-sanitizer", run: () => { const detail = safeSelfTestFailureDetail("network.search-detail-reader", new Error("https://e-hentai.org/g/123/token/ Cookie=secret")); assert(!/https?:|token|secret|\/g\//i.test(detail) && detail.includes("stage=network.search-detail-reader"), "self-test 失败信息泄漏") } },
  ]
  if (options.network) checks.push({ name: "network.search-detail-reader", run: async () => { const list = await searchGalleries("", getBaseUrl()); assert(list.items.length > 0, "画廊列表为空"); const detail = await loadGalleryDetailCore(list.items[0].url); assert(Boolean(detail.title) && detail.pageLinks.length > 0, "画廊详情或预览为空"); const image = await resolveImagePage(detail.pageLinks[0].pageUrl); assert(Boolean(image.imageUrl), "阅读器图片页未解析到图片") } })
  const results: SelfTestResult[] = []
  for (const check of checks) {
    const started = Date.now()
    try { await check.run(); results.push({ name: check.name, ok: true, durationMs: Date.now() - started }) }
    catch (error) { results.push({ name: check.name, ok: false, durationMs: Date.now() - started, detail: safeSelfTestFailureDetail(check.name, error) }) }
  }
  return results
}
